// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/rti/history.proto

package rti.amanzi;

public final class HistoryOuterClass {
  private HistoryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HistoryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rti.amanzi.History)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
     */
    boolean hasModifiedOn();
    /**
     * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
     */
    com.google.protobuf.Timestamp getModifiedOn();
    /**
     * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getModifiedOnOrBuilder();

    /**
     * <code>string comment = 2;</code>
     */
    java.lang.String getComment();
    /**
     * <code>string comment = 2;</code>
     */
    com.google.protobuf.ByteString
        getCommentBytes();

    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    java.util.List<java.lang.String>
        getReferenceIdsList();
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    int getReferenceIdsCount();
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    java.lang.String getReferenceIds(int index);
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    com.google.protobuf.ByteString
        getReferenceIdsBytes(int index);
  }
  /**
   * Protobuf type {@code rti.amanzi.History}
   */
  public  static final class History extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rti.amanzi.History)
      HistoryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use History.newBuilder() to construct.
    private History(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private History() {
      comment_ = "";
      referenceIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private History(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (modifiedOn_ != null) {
                subBuilder = modifiedOn_.toBuilder();
              }
              modifiedOn_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(modifiedOn_);
                modifiedOn_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              comment_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                referenceIds_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              referenceIds_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          referenceIds_ = referenceIds_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rti.amanzi.HistoryOuterClass.internal_static_rti_amanzi_History_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rti.amanzi.HistoryOuterClass.internal_static_rti_amanzi_History_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rti.amanzi.HistoryOuterClass.History.class, rti.amanzi.HistoryOuterClass.History.Builder.class);
    }

    private int bitField0_;
    public static final int MODIFIEDON_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp modifiedOn_;
    /**
     * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
     */
    public boolean hasModifiedOn() {
      return modifiedOn_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
     */
    public com.google.protobuf.Timestamp getModifiedOn() {
      return modifiedOn_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modifiedOn_;
    }
    /**
     * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getModifiedOnOrBuilder() {
      return getModifiedOn();
    }

    public static final int COMMENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object comment_;
    /**
     * <code>string comment = 2;</code>
     */
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comment_ = s;
        return s;
      }
    }
    /**
     * <code>string comment = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERENCEIDS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList referenceIds_;
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getReferenceIdsList() {
      return referenceIds_;
    }
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    public int getReferenceIdsCount() {
      return referenceIds_.size();
    }
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    public java.lang.String getReferenceIds(int index) {
      return referenceIds_.get(index);
    }
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReferenceIdsBytes(int index) {
      return referenceIds_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (modifiedOn_ != null) {
        output.writeMessage(1, getModifiedOn());
      }
      if (!getCommentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, comment_);
      }
      for (int i = 0; i < referenceIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, referenceIds_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (modifiedOn_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getModifiedOn());
      }
      if (!getCommentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, comment_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < referenceIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(referenceIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getReferenceIdsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rti.amanzi.HistoryOuterClass.History)) {
        return super.equals(obj);
      }
      rti.amanzi.HistoryOuterClass.History other = (rti.amanzi.HistoryOuterClass.History) obj;

      if (hasModifiedOn() != other.hasModifiedOn()) return false;
      if (hasModifiedOn()) {
        if (!getModifiedOn()
            .equals(other.getModifiedOn())) return false;
      }
      if (!getComment()
          .equals(other.getComment())) return false;
      if (!getReferenceIdsList()
          .equals(other.getReferenceIdsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasModifiedOn()) {
        hash = (37 * hash) + MODIFIEDON_FIELD_NUMBER;
        hash = (53 * hash) + getModifiedOn().hashCode();
      }
      hash = (37 * hash) + COMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getComment().hashCode();
      if (getReferenceIdsCount() > 0) {
        hash = (37 * hash) + REFERENCEIDS_FIELD_NUMBER;
        hash = (53 * hash) + getReferenceIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rti.amanzi.HistoryOuterClass.History parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rti.amanzi.HistoryOuterClass.History parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rti.amanzi.HistoryOuterClass.History parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rti.amanzi.HistoryOuterClass.History parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rti.amanzi.HistoryOuterClass.History parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rti.amanzi.HistoryOuterClass.History parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rti.amanzi.HistoryOuterClass.History parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rti.amanzi.HistoryOuterClass.History parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rti.amanzi.HistoryOuterClass.History parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rti.amanzi.HistoryOuterClass.History parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rti.amanzi.HistoryOuterClass.History parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rti.amanzi.HistoryOuterClass.History parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rti.amanzi.HistoryOuterClass.History prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rti.amanzi.History}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rti.amanzi.History)
        rti.amanzi.HistoryOuterClass.HistoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rti.amanzi.HistoryOuterClass.internal_static_rti_amanzi_History_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rti.amanzi.HistoryOuterClass.internal_static_rti_amanzi_History_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rti.amanzi.HistoryOuterClass.History.class, rti.amanzi.HistoryOuterClass.History.Builder.class);
      }

      // Construct using rti.amanzi.HistoryOuterClass.History.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (modifiedOnBuilder_ == null) {
          modifiedOn_ = null;
        } else {
          modifiedOn_ = null;
          modifiedOnBuilder_ = null;
        }
        comment_ = "";

        referenceIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rti.amanzi.HistoryOuterClass.internal_static_rti_amanzi_History_descriptor;
      }

      @java.lang.Override
      public rti.amanzi.HistoryOuterClass.History getDefaultInstanceForType() {
        return rti.amanzi.HistoryOuterClass.History.getDefaultInstance();
      }

      @java.lang.Override
      public rti.amanzi.HistoryOuterClass.History build() {
        rti.amanzi.HistoryOuterClass.History result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rti.amanzi.HistoryOuterClass.History buildPartial() {
        rti.amanzi.HistoryOuterClass.History result = new rti.amanzi.HistoryOuterClass.History(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (modifiedOnBuilder_ == null) {
          result.modifiedOn_ = modifiedOn_;
        } else {
          result.modifiedOn_ = modifiedOnBuilder_.build();
        }
        result.comment_ = comment_;
        if (((bitField0_ & 0x00000004) != 0)) {
          referenceIds_ = referenceIds_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.referenceIds_ = referenceIds_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rti.amanzi.HistoryOuterClass.History) {
          return mergeFrom((rti.amanzi.HistoryOuterClass.History)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rti.amanzi.HistoryOuterClass.History other) {
        if (other == rti.amanzi.HistoryOuterClass.History.getDefaultInstance()) return this;
        if (other.hasModifiedOn()) {
          mergeModifiedOn(other.getModifiedOn());
        }
        if (!other.getComment().isEmpty()) {
          comment_ = other.comment_;
          onChanged();
        }
        if (!other.referenceIds_.isEmpty()) {
          if (referenceIds_.isEmpty()) {
            referenceIds_ = other.referenceIds_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureReferenceIdsIsMutable();
            referenceIds_.addAll(other.referenceIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rti.amanzi.HistoryOuterClass.History parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rti.amanzi.HistoryOuterClass.History) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Timestamp modifiedOn_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> modifiedOnBuilder_;
      /**
       * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
       */
      public boolean hasModifiedOn() {
        return modifiedOnBuilder_ != null || modifiedOn_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
       */
      public com.google.protobuf.Timestamp getModifiedOn() {
        if (modifiedOnBuilder_ == null) {
          return modifiedOn_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modifiedOn_;
        } else {
          return modifiedOnBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
       */
      public Builder setModifiedOn(com.google.protobuf.Timestamp value) {
        if (modifiedOnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          modifiedOn_ = value;
          onChanged();
        } else {
          modifiedOnBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
       */
      public Builder setModifiedOn(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (modifiedOnBuilder_ == null) {
          modifiedOn_ = builderForValue.build();
          onChanged();
        } else {
          modifiedOnBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
       */
      public Builder mergeModifiedOn(com.google.protobuf.Timestamp value) {
        if (modifiedOnBuilder_ == null) {
          if (modifiedOn_ != null) {
            modifiedOn_ =
              com.google.protobuf.Timestamp.newBuilder(modifiedOn_).mergeFrom(value).buildPartial();
          } else {
            modifiedOn_ = value;
          }
          onChanged();
        } else {
          modifiedOnBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
       */
      public Builder clearModifiedOn() {
        if (modifiedOnBuilder_ == null) {
          modifiedOn_ = null;
          onChanged();
        } else {
          modifiedOn_ = null;
          modifiedOnBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getModifiedOnBuilder() {
        
        onChanged();
        return getModifiedOnFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getModifiedOnOrBuilder() {
        if (modifiedOnBuilder_ != null) {
          return modifiedOnBuilder_.getMessageOrBuilder();
        } else {
          return modifiedOn_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : modifiedOn_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp modifiedOn = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getModifiedOnFieldBuilder() {
        if (modifiedOnBuilder_ == null) {
          modifiedOnBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getModifiedOn(),
                  getParentForChildren(),
                  isClean());
          modifiedOn_ = null;
        }
        return modifiedOnBuilder_;
      }

      private java.lang.Object comment_ = "";
      /**
       * <code>string comment = 2;</code>
       */
      public java.lang.String getComment() {
        java.lang.Object ref = comment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          comment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string comment = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCommentBytes() {
        java.lang.Object ref = comment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string comment = 2;</code>
       */
      public Builder setComment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        comment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string comment = 2;</code>
       */
      public Builder clearComment() {
        
        comment_ = getDefaultInstance().getComment();
        onChanged();
        return this;
      }
      /**
       * <code>string comment = 2;</code>
       */
      public Builder setCommentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        comment_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList referenceIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureReferenceIdsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          referenceIds_ = new com.google.protobuf.LazyStringArrayList(referenceIds_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string referenceIds = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getReferenceIdsList() {
        return referenceIds_.getUnmodifiableView();
      }
      /**
       * <code>repeated string referenceIds = 3;</code>
       */
      public int getReferenceIdsCount() {
        return referenceIds_.size();
      }
      /**
       * <code>repeated string referenceIds = 3;</code>
       */
      public java.lang.String getReferenceIds(int index) {
        return referenceIds_.get(index);
      }
      /**
       * <code>repeated string referenceIds = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReferenceIdsBytes(int index) {
        return referenceIds_.getByteString(index);
      }
      /**
       * <code>repeated string referenceIds = 3;</code>
       */
      public Builder setReferenceIds(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReferenceIdsIsMutable();
        referenceIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string referenceIds = 3;</code>
       */
      public Builder addReferenceIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReferenceIdsIsMutable();
        referenceIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string referenceIds = 3;</code>
       */
      public Builder addAllReferenceIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureReferenceIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, referenceIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string referenceIds = 3;</code>
       */
      public Builder clearReferenceIds() {
        referenceIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string referenceIds = 3;</code>
       */
      public Builder addReferenceIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureReferenceIdsIsMutable();
        referenceIds_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rti.amanzi.History)
    }

    // @@protoc_insertion_point(class_scope:rti.amanzi.History)
    private static final rti.amanzi.HistoryOuterClass.History DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rti.amanzi.HistoryOuterClass.History();
    }

    public static rti.amanzi.HistoryOuterClass.History getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<History>
        PARSER = new com.google.protobuf.AbstractParser<History>() {
      @java.lang.Override
      public History parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new History(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<History> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<History> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rti.amanzi.HistoryOuterClass.History getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_History_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_History_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032protobuf/rti/history.proto\022\nrti.amanzi" +
      "\032\037protobuf/google/timestamp.proto\"`\n\007His" +
      "tory\022.\n\nmodifiedOn\030\001 \001(\0132\032.google.protob" +
      "uf.Timestamp\022\017\n\007comment\030\002 \001(\t\022\024\n\014referen" +
      "ceIds\030\003 \003(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_rti_amanzi_History_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rti_amanzi_History_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_History_descriptor,
        new java.lang.String[] { "ModifiedOn", "Comment", "ReferenceIds", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
