// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/rti/timeinterval.proto

package rti.amanzi;

public final class Timeinterval {
  private Timeinterval() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TimeIntervalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rti.amanzi.TimeInterval)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *The Interval representing the frequency of data e.g: PT1H (Every one hour)
     * </pre>
     *
     * <code>string interval = 1;</code>
     */
    java.lang.String getInterval();
    /**
     * <pre>
     *The Interval representing the frequency of data e.g: PT1H (Every one hour)
     * </pre>
     *
     * <code>string interval = 1;</code>
     */
    com.google.protobuf.ByteString
        getIntervalBytes();

    /**
     * <pre>
     *The timestamp of the first record in this timeseries
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    boolean hasStart();
    /**
     * <pre>
     *The timestamp of the first record in this timeseries
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    com.google.protobuf.Timestamp getStart();
    /**
     * <pre>
     *The timestamp of the first record in this timeseries
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getStartOrBuilder();

    /**
     * <pre>
     *The timestamp of the last record in this timeseries
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end = 3;</code>
     */
    boolean hasEnd();
    /**
     * <pre>
     *The timestamp of the last record in this timeseries
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end = 3;</code>
     */
    com.google.protobuf.Timestamp getEnd();
    /**
     * <pre>
     *The timestamp of the last record in this timeseries
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getEndOrBuilder();
  }
  /**
   * <pre>
   * Represents a Time Interval related to a timeseries object
   * A Time Interval is a iso 8601 duration indicating the frequency of data in the associated timeseries
   * https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_duration_format.htm
   * </pre>
   *
   * Protobuf type {@code rti.amanzi.TimeInterval}
   */
  public  static final class TimeInterval extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rti.amanzi.TimeInterval)
      TimeIntervalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TimeInterval.newBuilder() to construct.
    private TimeInterval(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TimeInterval() {
      interval_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TimeInterval(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              interval_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (start_ != null) {
                subBuilder = start_.toBuilder();
              }
              start_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(start_);
                start_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (end_ != null) {
                subBuilder = end_.toBuilder();
              }
              end_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(end_);
                end_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rti.amanzi.Timeinterval.internal_static_rti_amanzi_TimeInterval_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rti.amanzi.Timeinterval.internal_static_rti_amanzi_TimeInterval_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rti.amanzi.Timeinterval.TimeInterval.class, rti.amanzi.Timeinterval.TimeInterval.Builder.class);
    }

    public static final int INTERVAL_FIELD_NUMBER = 1;
    private volatile java.lang.Object interval_;
    /**
     * <pre>
     *The Interval representing the frequency of data e.g: PT1H (Every one hour)
     * </pre>
     *
     * <code>string interval = 1;</code>
     */
    public java.lang.String getInterval() {
      java.lang.Object ref = interval_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interval_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *The Interval representing the frequency of data e.g: PT1H (Every one hour)
     * </pre>
     *
     * <code>string interval = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIntervalBytes() {
      java.lang.Object ref = interval_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interval_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp start_;
    /**
     * <pre>
     *The timestamp of the first record in this timeseries
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    public boolean hasStart() {
      return start_ != null;
    }
    /**
     * <pre>
     *The timestamp of the first record in this timeseries
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    public com.google.protobuf.Timestamp getStart() {
      return start_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : start_;
    }
    /**
     * <pre>
     *The timestamp of the first record in this timeseries
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartOrBuilder() {
      return getStart();
    }

    public static final int END_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp end_;
    /**
     * <pre>
     *The timestamp of the last record in this timeseries
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end = 3;</code>
     */
    public boolean hasEnd() {
      return end_ != null;
    }
    /**
     * <pre>
     *The timestamp of the last record in this timeseries
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end = 3;</code>
     */
    public com.google.protobuf.Timestamp getEnd() {
      return end_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : end_;
    }
    /**
     * <pre>
     *The timestamp of the last record in this timeseries
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getEndOrBuilder() {
      return getEnd();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIntervalBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, interval_);
      }
      if (start_ != null) {
        output.writeMessage(2, getStart());
      }
      if (end_ != null) {
        output.writeMessage(3, getEnd());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIntervalBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, interval_);
      }
      if (start_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStart());
      }
      if (end_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getEnd());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rti.amanzi.Timeinterval.TimeInterval)) {
        return super.equals(obj);
      }
      rti.amanzi.Timeinterval.TimeInterval other = (rti.amanzi.Timeinterval.TimeInterval) obj;

      if (!getInterval()
          .equals(other.getInterval())) return false;
      if (hasStart() != other.hasStart()) return false;
      if (hasStart()) {
        if (!getStart()
            .equals(other.getStart())) return false;
      }
      if (hasEnd() != other.hasEnd()) return false;
      if (hasEnd()) {
        if (!getEnd()
            .equals(other.getEnd())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + getInterval().hashCode();
      if (hasStart()) {
        hash = (37 * hash) + START_FIELD_NUMBER;
        hash = (53 * hash) + getStart().hashCode();
      }
      if (hasEnd()) {
        hash = (37 * hash) + END_FIELD_NUMBER;
        hash = (53 * hash) + getEnd().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rti.amanzi.Timeinterval.TimeInterval parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rti.amanzi.Timeinterval.TimeInterval parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rti.amanzi.Timeinterval.TimeInterval parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rti.amanzi.Timeinterval.TimeInterval parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rti.amanzi.Timeinterval.TimeInterval parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rti.amanzi.Timeinterval.TimeInterval parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rti.amanzi.Timeinterval.TimeInterval parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rti.amanzi.Timeinterval.TimeInterval parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rti.amanzi.Timeinterval.TimeInterval parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rti.amanzi.Timeinterval.TimeInterval parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rti.amanzi.Timeinterval.TimeInterval parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rti.amanzi.Timeinterval.TimeInterval parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rti.amanzi.Timeinterval.TimeInterval prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Represents a Time Interval related to a timeseries object
     * A Time Interval is a iso 8601 duration indicating the frequency of data in the associated timeseries
     * https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_duration_format.htm
     * </pre>
     *
     * Protobuf type {@code rti.amanzi.TimeInterval}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rti.amanzi.TimeInterval)
        rti.amanzi.Timeinterval.TimeIntervalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rti.amanzi.Timeinterval.internal_static_rti_amanzi_TimeInterval_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rti.amanzi.Timeinterval.internal_static_rti_amanzi_TimeInterval_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rti.amanzi.Timeinterval.TimeInterval.class, rti.amanzi.Timeinterval.TimeInterval.Builder.class);
      }

      // Construct using rti.amanzi.Timeinterval.TimeInterval.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        interval_ = "";

        if (startBuilder_ == null) {
          start_ = null;
        } else {
          start_ = null;
          startBuilder_ = null;
        }
        if (endBuilder_ == null) {
          end_ = null;
        } else {
          end_ = null;
          endBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rti.amanzi.Timeinterval.internal_static_rti_amanzi_TimeInterval_descriptor;
      }

      @java.lang.Override
      public rti.amanzi.Timeinterval.TimeInterval getDefaultInstanceForType() {
        return rti.amanzi.Timeinterval.TimeInterval.getDefaultInstance();
      }

      @java.lang.Override
      public rti.amanzi.Timeinterval.TimeInterval build() {
        rti.amanzi.Timeinterval.TimeInterval result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rti.amanzi.Timeinterval.TimeInterval buildPartial() {
        rti.amanzi.Timeinterval.TimeInterval result = new rti.amanzi.Timeinterval.TimeInterval(this);
        result.interval_ = interval_;
        if (startBuilder_ == null) {
          result.start_ = start_;
        } else {
          result.start_ = startBuilder_.build();
        }
        if (endBuilder_ == null) {
          result.end_ = end_;
        } else {
          result.end_ = endBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rti.amanzi.Timeinterval.TimeInterval) {
          return mergeFrom((rti.amanzi.Timeinterval.TimeInterval)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rti.amanzi.Timeinterval.TimeInterval other) {
        if (other == rti.amanzi.Timeinterval.TimeInterval.getDefaultInstance()) return this;
        if (!other.getInterval().isEmpty()) {
          interval_ = other.interval_;
          onChanged();
        }
        if (other.hasStart()) {
          mergeStart(other.getStart());
        }
        if (other.hasEnd()) {
          mergeEnd(other.getEnd());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rti.amanzi.Timeinterval.TimeInterval parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rti.amanzi.Timeinterval.TimeInterval) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object interval_ = "";
      /**
       * <pre>
       *The Interval representing the frequency of data e.g: PT1H (Every one hour)
       * </pre>
       *
       * <code>string interval = 1;</code>
       */
      public java.lang.String getInterval() {
        java.lang.Object ref = interval_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          interval_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *The Interval representing the frequency of data e.g: PT1H (Every one hour)
       * </pre>
       *
       * <code>string interval = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIntervalBytes() {
        java.lang.Object ref = interval_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interval_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *The Interval representing the frequency of data e.g: PT1H (Every one hour)
       * </pre>
       *
       * <code>string interval = 1;</code>
       */
      public Builder setInterval(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        interval_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *The Interval representing the frequency of data e.g: PT1H (Every one hour)
       * </pre>
       *
       * <code>string interval = 1;</code>
       */
      public Builder clearInterval() {
        
        interval_ = getDefaultInstance().getInterval();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *The Interval representing the frequency of data e.g: PT1H (Every one hour)
       * </pre>
       *
       * <code>string interval = 1;</code>
       */
      public Builder setIntervalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        interval_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp start_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startBuilder_;
      /**
       * <pre>
       *The timestamp of the first record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public boolean hasStart() {
        return startBuilder_ != null || start_ != null;
      }
      /**
       * <pre>
       *The timestamp of the first record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public com.google.protobuf.Timestamp getStart() {
        if (startBuilder_ == null) {
          return start_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : start_;
        } else {
          return startBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *The timestamp of the first record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public Builder setStart(com.google.protobuf.Timestamp value) {
        if (startBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          start_ = value;
          onChanged();
        } else {
          startBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *The timestamp of the first record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public Builder setStart(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (startBuilder_ == null) {
          start_ = builderForValue.build();
          onChanged();
        } else {
          startBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *The timestamp of the first record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public Builder mergeStart(com.google.protobuf.Timestamp value) {
        if (startBuilder_ == null) {
          if (start_ != null) {
            start_ =
              com.google.protobuf.Timestamp.newBuilder(start_).mergeFrom(value).buildPartial();
          } else {
            start_ = value;
          }
          onChanged();
        } else {
          startBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *The timestamp of the first record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public Builder clearStart() {
        if (startBuilder_ == null) {
          start_ = null;
          onChanged();
        } else {
          start_ = null;
          startBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *The timestamp of the first record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getStartBuilder() {
        
        onChanged();
        return getStartFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *The timestamp of the first record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getStartOrBuilder() {
        if (startBuilder_ != null) {
          return startBuilder_.getMessageOrBuilder();
        } else {
          return start_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : start_;
        }
      }
      /**
       * <pre>
       *The timestamp of the first record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getStartFieldBuilder() {
        if (startBuilder_ == null) {
          startBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getStart(),
                  getParentForChildren(),
                  isClean());
          start_ = null;
        }
        return startBuilder_;
      }

      private com.google.protobuf.Timestamp end_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> endBuilder_;
      /**
       * <pre>
       *The timestamp of the last record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp end = 3;</code>
       */
      public boolean hasEnd() {
        return endBuilder_ != null || end_ != null;
      }
      /**
       * <pre>
       *The timestamp of the last record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp end = 3;</code>
       */
      public com.google.protobuf.Timestamp getEnd() {
        if (endBuilder_ == null) {
          return end_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : end_;
        } else {
          return endBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *The timestamp of the last record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp end = 3;</code>
       */
      public Builder setEnd(com.google.protobuf.Timestamp value) {
        if (endBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          end_ = value;
          onChanged();
        } else {
          endBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *The timestamp of the last record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp end = 3;</code>
       */
      public Builder setEnd(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (endBuilder_ == null) {
          end_ = builderForValue.build();
          onChanged();
        } else {
          endBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *The timestamp of the last record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp end = 3;</code>
       */
      public Builder mergeEnd(com.google.protobuf.Timestamp value) {
        if (endBuilder_ == null) {
          if (end_ != null) {
            end_ =
              com.google.protobuf.Timestamp.newBuilder(end_).mergeFrom(value).buildPartial();
          } else {
            end_ = value;
          }
          onChanged();
        } else {
          endBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *The timestamp of the last record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp end = 3;</code>
       */
      public Builder clearEnd() {
        if (endBuilder_ == null) {
          end_ = null;
          onChanged();
        } else {
          end_ = null;
          endBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *The timestamp of the last record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp end = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getEndBuilder() {
        
        onChanged();
        return getEndFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *The timestamp of the last record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp end = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getEndOrBuilder() {
        if (endBuilder_ != null) {
          return endBuilder_.getMessageOrBuilder();
        } else {
          return end_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : end_;
        }
      }
      /**
       * <pre>
       *The timestamp of the last record in this timeseries
       * </pre>
       *
       * <code>.google.protobuf.Timestamp end = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getEndFieldBuilder() {
        if (endBuilder_ == null) {
          endBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getEnd(),
                  getParentForChildren(),
                  isClean());
          end_ = null;
        }
        return endBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rti.amanzi.TimeInterval)
    }

    // @@protoc_insertion_point(class_scope:rti.amanzi.TimeInterval)
    private static final rti.amanzi.Timeinterval.TimeInterval DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rti.amanzi.Timeinterval.TimeInterval();
    }

    public static rti.amanzi.Timeinterval.TimeInterval getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TimeInterval>
        PARSER = new com.google.protobuf.AbstractParser<TimeInterval>() {
      @java.lang.Override
      public TimeInterval parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TimeInterval(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TimeInterval> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TimeInterval> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rti.amanzi.Timeinterval.TimeInterval getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_TimeInterval_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_TimeInterval_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037protobuf/rti/timeinterval.proto\022\nrti.a" +
      "manzi\032\037protobuf/google/timestamp.proto\"t" +
      "\n\014TimeInterval\022\020\n\010interval\030\001 \001(\t\022)\n\005star" +
      "t\030\002 \001(\0132\032.google.protobuf.Timestamp\022\'\n\003e" +
      "nd\030\003 \001(\0132\032.google.protobuf.Timestampb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_rti_amanzi_TimeInterval_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rti_amanzi_TimeInterval_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_TimeInterval_descriptor,
        new java.lang.String[] { "Interval", "Start", "End", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
