// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

public final class Amanzi {
  private Amanzi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_Struct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_Struct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_Struct_FieldsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_Struct_FieldsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_NumberValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_NumberValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_Value_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_ListValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_ListValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_Timestamp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_Timestamp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_Source_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_Source_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_Elevation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_Elevation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_SourceLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_SourceLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_Parameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_Parameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_TimeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_TimeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_Origin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_Origin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_Group_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_Group_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_TimeSeriesMetaInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_TimeSeriesMetaInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_TimeRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_TimeRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rti_amanzi_protobuf_TimeSeries_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rti_amanzi_protobuf_TimeSeries_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014amanzi.proto\022\023rti.amanzi.protobuf\"\214\001\n\006" +
      "Struct\0227\n\006fields\030\001 \003(\0132\'.rti.amanzi.prot" +
      "obuf.Struct.FieldsEntry\032I\n\013FieldsEntry\022\013" +
      "\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\0132\032.rti.amanzi." +
      "protobuf.Value:\0028\001\"\330\001\n\013NumberValue\022\026\n\014do" +
      "uble_value\030\001 \001(\001H\000\022\025\n\013float_value\030\002 \001(\002H" +
      "\000\022\025\n\013int64_value\030\003 \001(\003H\000\022\025\n\013int32_value\030" +
      "\004 \001(\005H\000\022\026\n\014uint64_value\030\005 \001(\004H\000\022\026\n\014unit3" +
      "2_value\030\006 \001(\rH\000\0224\n\nnull_value\030\007 \001(\0162\036.rt" +
      "i.amanzi.protobuf.NullValueH\000B\006\n\004kind\"\366\001" +
      "\n\005Value\0224\n\nnull_value\030\001 \001(\0162\036.rti.amanzi" +
      ".protobuf.NullValueH\000\022\026\n\014number_value\030\002 " +
      "\001(\001H\000\022\026\n\014string_value\030\003 \001(\tH\000\022\024\n\nbool_va" +
      "lue\030\004 \001(\010H\000\0223\n\014struct_value\030\005 \001(\0132\033.rti." +
      "amanzi.protobuf.StructH\000\0224\n\nlist_value\030\006" +
      " \001(\0132\036.rti.amanzi.protobuf.ListValueH\000B\006" +
      "\n\004kind\"7\n\tListValue\022*\n\006values\030\001 \003(\0132\032.rt" +
      "i.amanzi.protobuf.Value\"+\n\tTimestamp\022\017\n\007" +
      "seconds\030\001 \001(\003\022\r\n\005nanos\030\002 \001(\005\"$\n\006Source\022\014" +
      "\n\004name\030\001 \001(\t\022\014\n\004code\030\002 \001(\t\"8\n\tElevation\022" +
      "\r\n\005value\030\001 \001(\001\022\r\n\005units\030\002 \001(\t\022\r\n\005datum\030\003" +
      " \001(\t\"_\n\016SourceLocation\022\014\n\004name\030\001 \001(\t\022\014\n\004" +
      "code\030\002 \001(\t\0221\n\televation\030\003 \001(\0132\036.rti.aman" +
      "zi.protobuf.Elevation\"6\n\tParameter\022\014\n\004na" +
      "me\030\001 \001(\t\022\014\n\004code\030\002 \001(\t\022\r\n\005units\030\003 \001(\t\"\257\001" +
      "\n\010TimeInfo\0225\n\rreferenceTime\030\001 \001(\0132\036.rti." +
      "amanzi.protobuf.Timestamp\022-\n\005start\030\002 \001(\013" +
      "2\036.rti.amanzi.protobuf.Timestamp\022+\n\003end\030" +
      "\003 \001(\0132\036.rti.amanzi.protobuf.Timestamp\022\020\n" +
      "\010interval\030\004 \001(\t\"g\n\006Origin\0222\n\nmodifiedOn\030" +
      "\001 \001(\0132\036.rti.amanzi.protobuf.Timestamp\022\023\n" +
      "\013description\030\002 \001(\t\022\024\n\014referenceIds\030\003 \003(\t" +
      "\"-\n\005Group\022\017\n\007groupId\030\001 \001(\t\022\023\n\013descriptio" +
      "n\030\002 \001(\t\"\242\003\n\022TimeSeriesMetaInfo\022\n\n\002id\030\001 \001" +
      "(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004code\030\003 \001(\t\022\014\n\004type\030\004" +
      " \001(\t\022/\n\nproperties\030\005 \001(\0132\033.rti.amanzi.pr" +
      "otobuf.Struct\022*\n\006groups\030\006 \003(\0132\032.rti.aman" +
      "zi.protobuf.Group\022+\n\006source\030\007 \001(\0132\033.rti." +
      "amanzi.protobuf.Source\022;\n\016sourceLocation" +
      "\030\010 \001(\0132#.rti.amanzi.protobuf.SourceLocat" +
      "ion\0221\n\tparameter\030\t \001(\0132\036.rti.amanzi.prot" +
      "obuf.Parameter\022/\n\010timeInfo\030\n \001(\0132\035.rti.a" +
      "manzi.protobuf.TimeInfo\022+\n\006origin\030\013 \001(\0132" +
      "\033.rti.amanzi.protobuf.Origin\"\264\001\n\nTimeRec" +
      "ord\0220\n\010datetime\030\001 \001(\0132\036.rti.amanzi.proto" +
      "buf.Timestamp\022/\n\005value\030\002 \001(\0132 .rti.amanz" +
      "i.protobuf.NumberValue\022\022\n\nqualifiers\030\003 \003" +
      "(\t\022/\n\nproperties\030\004 \001(\0132\033.rti.amanzi.prot" +
      "obuf.Struct\"v\n\nTimeSeries\0229\n\010metaInfo\030\003 " +
      "\001(\0132\'.rti.amanzi.protobuf.TimeSeriesMeta" +
      "Info\022-\n\004data\030\004 \003(\0132\037.rti.amanzi.protobuf" +
      ".TimeRecord*\033\n\tNullValue\022\016\n\nNULL_VALUE\020\000" +
      "B\033\n\027org.rti.amanzi.protobufP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_rti_amanzi_protobuf_Struct_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rti_amanzi_protobuf_Struct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_Struct_descriptor,
        new java.lang.String[] { "Fields", });
    internal_static_rti_amanzi_protobuf_Struct_FieldsEntry_descriptor =
      internal_static_rti_amanzi_protobuf_Struct_descriptor.getNestedTypes().get(0);
    internal_static_rti_amanzi_protobuf_Struct_FieldsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_Struct_FieldsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rti_amanzi_protobuf_NumberValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rti_amanzi_protobuf_NumberValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_NumberValue_descriptor,
        new java.lang.String[] { "DoubleValue", "FloatValue", "Int64Value", "Int32Value", "Uint64Value", "Unit32Value", "NullValue", "Kind", });
    internal_static_rti_amanzi_protobuf_Value_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rti_amanzi_protobuf_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_Value_descriptor,
        new java.lang.String[] { "NullValue", "NumberValue", "StringValue", "BoolValue", "StructValue", "ListValue", "Kind", });
    internal_static_rti_amanzi_protobuf_ListValue_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_rti_amanzi_protobuf_ListValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_ListValue_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_rti_amanzi_protobuf_Timestamp_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_rti_amanzi_protobuf_Timestamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_Timestamp_descriptor,
        new java.lang.String[] { "Seconds", "Nanos", });
    internal_static_rti_amanzi_protobuf_Source_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_rti_amanzi_protobuf_Source_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_Source_descriptor,
        new java.lang.String[] { "Name", "Code", });
    internal_static_rti_amanzi_protobuf_Elevation_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_rti_amanzi_protobuf_Elevation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_Elevation_descriptor,
        new java.lang.String[] { "Value", "Units", "Datum", });
    internal_static_rti_amanzi_protobuf_SourceLocation_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_rti_amanzi_protobuf_SourceLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_SourceLocation_descriptor,
        new java.lang.String[] { "Name", "Code", "Elevation", });
    internal_static_rti_amanzi_protobuf_Parameter_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_rti_amanzi_protobuf_Parameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_Parameter_descriptor,
        new java.lang.String[] { "Name", "Code", "Units", });
    internal_static_rti_amanzi_protobuf_TimeInfo_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_rti_amanzi_protobuf_TimeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_TimeInfo_descriptor,
        new java.lang.String[] { "ReferenceTime", "Start", "End", "Interval", });
    internal_static_rti_amanzi_protobuf_Origin_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_rti_amanzi_protobuf_Origin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_Origin_descriptor,
        new java.lang.String[] { "ModifiedOn", "Description", "ReferenceIds", });
    internal_static_rti_amanzi_protobuf_Group_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_rti_amanzi_protobuf_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_Group_descriptor,
        new java.lang.String[] { "GroupId", "Description", });
    internal_static_rti_amanzi_protobuf_TimeSeriesMetaInfo_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_rti_amanzi_protobuf_TimeSeriesMetaInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_TimeSeriesMetaInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "Code", "Type", "Properties", "Groups", "Source", "SourceLocation", "Parameter", "TimeInfo", "Origin", });
    internal_static_rti_amanzi_protobuf_TimeRecord_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_rti_amanzi_protobuf_TimeRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_TimeRecord_descriptor,
        new java.lang.String[] { "Datetime", "Value", "Qualifiers", "Properties", });
    internal_static_rti_amanzi_protobuf_TimeSeries_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_rti_amanzi_protobuf_TimeSeries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rti_amanzi_protobuf_TimeSeries_descriptor,
        new java.lang.String[] { "MetaInfo", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
