// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

/**
 * Protobuf type {@code rti.amanzi.protobuf.Elevation}
 */
public  final class Elevation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rti.amanzi.protobuf.Elevation)
    ElevationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Elevation.newBuilder() to construct.
  private Elevation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Elevation() {
    units_ = "";
    datum_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Elevation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            value_ = input.readDouble();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            units_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            datum_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_Elevation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_Elevation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.rti.amanzi.protobuf.Elevation.class, org.rti.amanzi.protobuf.Elevation.Builder.class);
  }

  public static final int VALUE_FIELD_NUMBER = 1;
  private double value_;
  /**
   * <code>double value = 1;</code>
   */
  public double getValue() {
    return value_;
  }

  public static final int UNITS_FIELD_NUMBER = 2;
  private volatile java.lang.Object units_;
  /**
   * <code>string units = 2;</code>
   */
  public java.lang.String getUnits() {
    java.lang.Object ref = units_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      units_ = s;
      return s;
    }
  }
  /**
   * <code>string units = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUnitsBytes() {
    java.lang.Object ref = units_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      units_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATUM_FIELD_NUMBER = 3;
  private volatile java.lang.Object datum_;
  /**
   * <code>string datum = 3;</code>
   */
  public java.lang.String getDatum() {
    java.lang.Object ref = datum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      datum_ = s;
      return s;
    }
  }
  /**
   * <code>string datum = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDatumBytes() {
    java.lang.Object ref = datum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      datum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (value_ != 0D) {
      output.writeDouble(1, value_);
    }
    if (!getUnitsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, units_);
    }
    if (!getDatumBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, datum_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (value_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, value_);
    }
    if (!getUnitsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, units_);
    }
    if (!getDatumBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, datum_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.rti.amanzi.protobuf.Elevation)) {
      return super.equals(obj);
    }
    org.rti.amanzi.protobuf.Elevation other = (org.rti.amanzi.protobuf.Elevation) obj;

    if (java.lang.Double.doubleToLongBits(getValue())
        != java.lang.Double.doubleToLongBits(
            other.getValue())) return false;
    if (!getUnits()
        .equals(other.getUnits())) return false;
    if (!getDatum()
        .equals(other.getDatum())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getValue()));
    hash = (37 * hash) + UNITS_FIELD_NUMBER;
    hash = (53 * hash) + getUnits().hashCode();
    hash = (37 * hash) + DATUM_FIELD_NUMBER;
    hash = (53 * hash) + getDatum().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.rti.amanzi.protobuf.Elevation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.Elevation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.Elevation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.Elevation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.Elevation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.Elevation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.Elevation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.Elevation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.Elevation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.Elevation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.Elevation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.Elevation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.rti.amanzi.protobuf.Elevation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rti.amanzi.protobuf.Elevation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rti.amanzi.protobuf.Elevation)
      org.rti.amanzi.protobuf.ElevationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_Elevation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_Elevation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rti.amanzi.protobuf.Elevation.class, org.rti.amanzi.protobuf.Elevation.Builder.class);
    }

    // Construct using org.rti.amanzi.protobuf.Elevation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      value_ = 0D;

      units_ = "";

      datum_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_Elevation_descriptor;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.Elevation getDefaultInstanceForType() {
      return org.rti.amanzi.protobuf.Elevation.getDefaultInstance();
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.Elevation build() {
      org.rti.amanzi.protobuf.Elevation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.Elevation buildPartial() {
      org.rti.amanzi.protobuf.Elevation result = new org.rti.amanzi.protobuf.Elevation(this);
      result.value_ = value_;
      result.units_ = units_;
      result.datum_ = datum_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.rti.amanzi.protobuf.Elevation) {
        return mergeFrom((org.rti.amanzi.protobuf.Elevation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.rti.amanzi.protobuf.Elevation other) {
      if (other == org.rti.amanzi.protobuf.Elevation.getDefaultInstance()) return this;
      if (other.getValue() != 0D) {
        setValue(other.getValue());
      }
      if (!other.getUnits().isEmpty()) {
        units_ = other.units_;
        onChanged();
      }
      if (!other.getDatum().isEmpty()) {
        datum_ = other.datum_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.rti.amanzi.protobuf.Elevation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.rti.amanzi.protobuf.Elevation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double value_ ;
    /**
     * <code>double value = 1;</code>
     */
    public double getValue() {
      return value_;
    }
    /**
     * <code>double value = 1;</code>
     */
    public Builder setValue(double value) {
      
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double value = 1;</code>
     */
    public Builder clearValue() {
      
      value_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object units_ = "";
    /**
     * <code>string units = 2;</code>
     */
    public java.lang.String getUnits() {
      java.lang.Object ref = units_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        units_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string units = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUnitsBytes() {
      java.lang.Object ref = units_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        units_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string units = 2;</code>
     */
    public Builder setUnits(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      units_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string units = 2;</code>
     */
    public Builder clearUnits() {
      
      units_ = getDefaultInstance().getUnits();
      onChanged();
      return this;
    }
    /**
     * <code>string units = 2;</code>
     */
    public Builder setUnitsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      units_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object datum_ = "";
    /**
     * <code>string datum = 3;</code>
     */
    public java.lang.String getDatum() {
      java.lang.Object ref = datum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        datum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string datum = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDatumBytes() {
      java.lang.Object ref = datum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string datum = 3;</code>
     */
    public Builder setDatum(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      datum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string datum = 3;</code>
     */
    public Builder clearDatum() {
      
      datum_ = getDefaultInstance().getDatum();
      onChanged();
      return this;
    }
    /**
     * <code>string datum = 3;</code>
     */
    public Builder setDatumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      datum_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rti.amanzi.protobuf.Elevation)
  }

  // @@protoc_insertion_point(class_scope:rti.amanzi.protobuf.Elevation)
  private static final org.rti.amanzi.protobuf.Elevation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.rti.amanzi.protobuf.Elevation();
  }

  public static org.rti.amanzi.protobuf.Elevation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Elevation>
      PARSER = new com.google.protobuf.AbstractParser<Elevation>() {
    @java.lang.Override
    public Elevation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Elevation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Elevation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Elevation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.rti.amanzi.protobuf.Elevation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

