// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

public interface GroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti.amanzi.protobuf.Group)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string groupId = 1;</code>
   */
  java.lang.String getGroupId();
  /**
   * <code>string groupId = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupIdBytes();

  /**
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
