// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

/**
 * Protobuf type {@code rti.amanzi.protobuf.NumberValue}
 */
public  final class NumberValue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rti.amanzi.protobuf.NumberValue)
    NumberValueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NumberValue.newBuilder() to construct.
  private NumberValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NumberValue() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NumberValue(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {
            kindCase_ = 1;
            kind_ = input.readDouble();
            break;
          }
          case 21: {
            kindCase_ = 2;
            kind_ = input.readFloat();
            break;
          }
          case 24: {
            kindCase_ = 3;
            kind_ = input.readInt64();
            break;
          }
          case 32: {
            kindCase_ = 4;
            kind_ = input.readInt32();
            break;
          }
          case 40: {
            kindCase_ = 5;
            kind_ = input.readUInt64();
            break;
          }
          case 48: {
            kindCase_ = 6;
            kind_ = input.readUInt32();
            break;
          }
          case 56: {
            int rawValue = input.readEnum();
            kindCase_ = 7;
            kind_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_NumberValue_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_NumberValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.rti.amanzi.protobuf.NumberValue.class, org.rti.amanzi.protobuf.NumberValue.Builder.class);
  }

  private int kindCase_ = 0;
  private java.lang.Object kind_;
  public enum KindCase
      implements com.google.protobuf.Internal.EnumLite {
    DOUBLE_VALUE(1),
    FLOAT_VALUE(2),
    INT64_VALUE(3),
    INT32_VALUE(4),
    UINT64_VALUE(5),
    UNIT32_VALUE(6),
    NULL_VALUE(7),
    KIND_NOT_SET(0);
    private final int value;
    private KindCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static KindCase valueOf(int value) {
      return forNumber(value);
    }

    public static KindCase forNumber(int value) {
      switch (value) {
        case 1: return DOUBLE_VALUE;
        case 2: return FLOAT_VALUE;
        case 3: return INT64_VALUE;
        case 4: return INT32_VALUE;
        case 5: return UINT64_VALUE;
        case 6: return UNIT32_VALUE;
        case 7: return NULL_VALUE;
        case 0: return KIND_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public KindCase
  getKindCase() {
    return KindCase.forNumber(
        kindCase_);
  }

  public static final int DOUBLE_VALUE_FIELD_NUMBER = 1;
  /**
   * <code>double double_value = 1;</code>
   */
  public double getDoubleValue() {
    if (kindCase_ == 1) {
      return (java.lang.Double) kind_;
    }
    return 0D;
  }

  public static final int FLOAT_VALUE_FIELD_NUMBER = 2;
  /**
   * <code>float float_value = 2;</code>
   */
  public float getFloatValue() {
    if (kindCase_ == 2) {
      return (java.lang.Float) kind_;
    }
    return 0F;
  }

  public static final int INT64_VALUE_FIELD_NUMBER = 3;
  /**
   * <code>int64 int64_value = 3;</code>
   */
  public long getInt64Value() {
    if (kindCase_ == 3) {
      return (java.lang.Long) kind_;
    }
    return 0L;
  }

  public static final int INT32_VALUE_FIELD_NUMBER = 4;
  /**
   * <code>int32 int32_value = 4;</code>
   */
  public int getInt32Value() {
    if (kindCase_ == 4) {
      return (java.lang.Integer) kind_;
    }
    return 0;
  }

  public static final int UINT64_VALUE_FIELD_NUMBER = 5;
  /**
   * <code>uint64 uint64_value = 5;</code>
   */
  public long getUint64Value() {
    if (kindCase_ == 5) {
      return (java.lang.Long) kind_;
    }
    return 0L;
  }

  public static final int UNIT32_VALUE_FIELD_NUMBER = 6;
  /**
   * <code>uint32 unit32_value = 6;</code>
   */
  public int getUnit32Value() {
    if (kindCase_ == 6) {
      return (java.lang.Integer) kind_;
    }
    return 0;
  }

  public static final int NULL_VALUE_FIELD_NUMBER = 7;
  /**
   * <code>.rti.amanzi.protobuf.NullValue null_value = 7;</code>
   */
  public int getNullValueValue() {
    if (kindCase_ == 7) {
      return (java.lang.Integer) kind_;
    }
    return 0;
  }
  /**
   * <code>.rti.amanzi.protobuf.NullValue null_value = 7;</code>
   */
  public org.rti.amanzi.protobuf.NullValue getNullValue() {
    if (kindCase_ == 7) {
      @SuppressWarnings("deprecation")
      org.rti.amanzi.protobuf.NullValue result = org.rti.amanzi.protobuf.NullValue.valueOf(
          (java.lang.Integer) kind_);
      return result == null ? org.rti.amanzi.protobuf.NullValue.UNRECOGNIZED : result;
    }
    return org.rti.amanzi.protobuf.NullValue.NULL_VALUE;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kindCase_ == 1) {
      output.writeDouble(
          1, (double)((java.lang.Double) kind_));
    }
    if (kindCase_ == 2) {
      output.writeFloat(
          2, (float)((java.lang.Float) kind_));
    }
    if (kindCase_ == 3) {
      output.writeInt64(
          3, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 4) {
      output.writeInt32(
          4, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 5) {
      output.writeUInt64(
          5, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 6) {
      output.writeUInt32(
          6, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 7) {
      output.writeEnum(7, ((java.lang.Integer) kind_));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kindCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(
            1, (double)((java.lang.Double) kind_));
    }
    if (kindCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(
            2, (float)((java.lang.Float) kind_));
    }
    if (kindCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            3, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            4, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(
            5, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(
            6, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, ((java.lang.Integer) kind_));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.rti.amanzi.protobuf.NumberValue)) {
      return super.equals(obj);
    }
    org.rti.amanzi.protobuf.NumberValue other = (org.rti.amanzi.protobuf.NumberValue) obj;

    if (!getKindCase().equals(other.getKindCase())) return false;
    switch (kindCase_) {
      case 1:
        if (java.lang.Double.doubleToLongBits(getDoubleValue())
            != java.lang.Double.doubleToLongBits(
                other.getDoubleValue())) return false;
        break;
      case 2:
        if (java.lang.Float.floatToIntBits(getFloatValue())
            != java.lang.Float.floatToIntBits(
                other.getFloatValue())) return false;
        break;
      case 3:
        if (getInt64Value()
            != other.getInt64Value()) return false;
        break;
      case 4:
        if (getInt32Value()
            != other.getInt32Value()) return false;
        break;
      case 5:
        if (getUint64Value()
            != other.getUint64Value()) return false;
        break;
      case 6:
        if (getUnit32Value()
            != other.getUnit32Value()) return false;
        break;
      case 7:
        if (getNullValueValue()
            != other.getNullValueValue()) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (kindCase_) {
      case 1:
        hash = (37 * hash) + DOUBLE_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDoubleValue()));
        break;
      case 2:
        hash = (37 * hash) + FLOAT_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getFloatValue());
        break;
      case 3:
        hash = (37 * hash) + INT64_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getInt64Value());
        break;
      case 4:
        hash = (37 * hash) + INT32_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getInt32Value();
        break;
      case 5:
        hash = (37 * hash) + UINT64_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUint64Value());
        break;
      case 6:
        hash = (37 * hash) + UNIT32_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getUnit32Value();
        break;
      case 7:
        hash = (37 * hash) + NULL_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getNullValueValue();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.rti.amanzi.protobuf.NumberValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.NumberValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.NumberValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.NumberValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.NumberValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.NumberValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.NumberValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.NumberValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.NumberValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.NumberValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.NumberValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.NumberValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.rti.amanzi.protobuf.NumberValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rti.amanzi.protobuf.NumberValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rti.amanzi.protobuf.NumberValue)
      org.rti.amanzi.protobuf.NumberValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_NumberValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_NumberValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rti.amanzi.protobuf.NumberValue.class, org.rti.amanzi.protobuf.NumberValue.Builder.class);
    }

    // Construct using org.rti.amanzi.protobuf.NumberValue.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      kindCase_ = 0;
      kind_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_NumberValue_descriptor;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.NumberValue getDefaultInstanceForType() {
      return org.rti.amanzi.protobuf.NumberValue.getDefaultInstance();
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.NumberValue build() {
      org.rti.amanzi.protobuf.NumberValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.NumberValue buildPartial() {
      org.rti.amanzi.protobuf.NumberValue result = new org.rti.amanzi.protobuf.NumberValue(this);
      if (kindCase_ == 1) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 2) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 3) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 4) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 5) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 6) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 7) {
        result.kind_ = kind_;
      }
      result.kindCase_ = kindCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.rti.amanzi.protobuf.NumberValue) {
        return mergeFrom((org.rti.amanzi.protobuf.NumberValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.rti.amanzi.protobuf.NumberValue other) {
      if (other == org.rti.amanzi.protobuf.NumberValue.getDefaultInstance()) return this;
      switch (other.getKindCase()) {
        case DOUBLE_VALUE: {
          setDoubleValue(other.getDoubleValue());
          break;
        }
        case FLOAT_VALUE: {
          setFloatValue(other.getFloatValue());
          break;
        }
        case INT64_VALUE: {
          setInt64Value(other.getInt64Value());
          break;
        }
        case INT32_VALUE: {
          setInt32Value(other.getInt32Value());
          break;
        }
        case UINT64_VALUE: {
          setUint64Value(other.getUint64Value());
          break;
        }
        case UNIT32_VALUE: {
          setUnit32Value(other.getUnit32Value());
          break;
        }
        case NULL_VALUE: {
          setNullValueValue(other.getNullValueValue());
          break;
        }
        case KIND_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.rti.amanzi.protobuf.NumberValue parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.rti.amanzi.protobuf.NumberValue) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int kindCase_ = 0;
    private java.lang.Object kind_;
    public KindCase
        getKindCase() {
      return KindCase.forNumber(
          kindCase_);
    }

    public Builder clearKind() {
      kindCase_ = 0;
      kind_ = null;
      onChanged();
      return this;
    }


    /**
     * <code>double double_value = 1;</code>
     */
    public double getDoubleValue() {
      if (kindCase_ == 1) {
        return (java.lang.Double) kind_;
      }
      return 0D;
    }
    /**
     * <code>double double_value = 1;</code>
     */
    public Builder setDoubleValue(double value) {
      kindCase_ = 1;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double double_value = 1;</code>
     */
    public Builder clearDoubleValue() {
      if (kindCase_ == 1) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>float float_value = 2;</code>
     */
    public float getFloatValue() {
      if (kindCase_ == 2) {
        return (java.lang.Float) kind_;
      }
      return 0F;
    }
    /**
     * <code>float float_value = 2;</code>
     */
    public Builder setFloatValue(float value) {
      kindCase_ = 2;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float float_value = 2;</code>
     */
    public Builder clearFloatValue() {
      if (kindCase_ == 2) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>int64 int64_value = 3;</code>
     */
    public long getInt64Value() {
      if (kindCase_ == 3) {
        return (java.lang.Long) kind_;
      }
      return 0L;
    }
    /**
     * <code>int64 int64_value = 3;</code>
     */
    public Builder setInt64Value(long value) {
      kindCase_ = 3;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 int64_value = 3;</code>
     */
    public Builder clearInt64Value() {
      if (kindCase_ == 3) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>int32 int32_value = 4;</code>
     */
    public int getInt32Value() {
      if (kindCase_ == 4) {
        return (java.lang.Integer) kind_;
      }
      return 0;
    }
    /**
     * <code>int32 int32_value = 4;</code>
     */
    public Builder setInt32Value(int value) {
      kindCase_ = 4;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 int32_value = 4;</code>
     */
    public Builder clearInt32Value() {
      if (kindCase_ == 4) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>uint64 uint64_value = 5;</code>
     */
    public long getUint64Value() {
      if (kindCase_ == 5) {
        return (java.lang.Long) kind_;
      }
      return 0L;
    }
    /**
     * <code>uint64 uint64_value = 5;</code>
     */
    public Builder setUint64Value(long value) {
      kindCase_ = 5;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 uint64_value = 5;</code>
     */
    public Builder clearUint64Value() {
      if (kindCase_ == 5) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>uint32 unit32_value = 6;</code>
     */
    public int getUnit32Value() {
      if (kindCase_ == 6) {
        return (java.lang.Integer) kind_;
      }
      return 0;
    }
    /**
     * <code>uint32 unit32_value = 6;</code>
     */
    public Builder setUnit32Value(int value) {
      kindCase_ = 6;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 unit32_value = 6;</code>
     */
    public Builder clearUnit32Value() {
      if (kindCase_ == 6) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>.rti.amanzi.protobuf.NullValue null_value = 7;</code>
     */
    public int getNullValueValue() {
      if (kindCase_ == 7) {
        return ((java.lang.Integer) kind_).intValue();
      }
      return 0;
    }
    /**
     * <code>.rti.amanzi.protobuf.NullValue null_value = 7;</code>
     */
    public Builder setNullValueValue(int value) {
      kindCase_ = 7;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.NullValue null_value = 7;</code>
     */
    public org.rti.amanzi.protobuf.NullValue getNullValue() {
      if (kindCase_ == 7) {
        @SuppressWarnings("deprecation")
        org.rti.amanzi.protobuf.NullValue result = org.rti.amanzi.protobuf.NullValue.valueOf(
            (java.lang.Integer) kind_);
        return result == null ? org.rti.amanzi.protobuf.NullValue.UNRECOGNIZED : result;
      }
      return org.rti.amanzi.protobuf.NullValue.NULL_VALUE;
    }
    /**
     * <code>.rti.amanzi.protobuf.NullValue null_value = 7;</code>
     */
    public Builder setNullValue(org.rti.amanzi.protobuf.NullValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      kindCase_ = 7;
      kind_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.NullValue null_value = 7;</code>
     */
    public Builder clearNullValue() {
      if (kindCase_ == 7) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rti.amanzi.protobuf.NumberValue)
  }

  // @@protoc_insertion_point(class_scope:rti.amanzi.protobuf.NumberValue)
  private static final org.rti.amanzi.protobuf.NumberValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.rti.amanzi.protobuf.NumberValue();
  }

  public static org.rti.amanzi.protobuf.NumberValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NumberValue>
      PARSER = new com.google.protobuf.AbstractParser<NumberValue>() {
    @java.lang.Override
    public NumberValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NumberValue(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NumberValue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NumberValue> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.rti.amanzi.protobuf.NumberValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

