// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

/**
 * Protobuf type {@code rti.amanzi.protobuf.Origin}
 */
public  final class Origin extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rti.amanzi.protobuf.Origin)
    OriginOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Origin.newBuilder() to construct.
  private Origin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Origin() {
    description_ = "";
    referenceIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Origin(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.rti.amanzi.protobuf.Timestamp.Builder subBuilder = null;
            if (modifiedOn_ != null) {
              subBuilder = modifiedOn_.toBuilder();
            }
            modifiedOn_ = input.readMessage(org.rti.amanzi.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(modifiedOn_);
              modifiedOn_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              referenceIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            referenceIds_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        referenceIds_ = referenceIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_Origin_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_Origin_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.rti.amanzi.protobuf.Origin.class, org.rti.amanzi.protobuf.Origin.Builder.class);
  }

  private int bitField0_;
  public static final int MODIFIEDON_FIELD_NUMBER = 1;
  private org.rti.amanzi.protobuf.Timestamp modifiedOn_;
  /**
   * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
   */
  public boolean hasModifiedOn() {
    return modifiedOn_ != null;
  }
  /**
   * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
   */
  public org.rti.amanzi.protobuf.Timestamp getModifiedOn() {
    return modifiedOn_ == null ? org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : modifiedOn_;
  }
  /**
   * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
   */
  public org.rti.amanzi.protobuf.TimestampOrBuilder getModifiedOnOrBuilder() {
    return getModifiedOn();
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 2;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REFERENCEIDS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList referenceIds_;
  /**
   * <code>repeated string referenceIds = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getReferenceIdsList() {
    return referenceIds_;
  }
  /**
   * <code>repeated string referenceIds = 3;</code>
   */
  public int getReferenceIdsCount() {
    return referenceIds_.size();
  }
  /**
   * <code>repeated string referenceIds = 3;</code>
   */
  public java.lang.String getReferenceIds(int index) {
    return referenceIds_.get(index);
  }
  /**
   * <code>repeated string referenceIds = 3;</code>
   */
  public com.google.protobuf.ByteString
      getReferenceIdsBytes(int index) {
    return referenceIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (modifiedOn_ != null) {
      output.writeMessage(1, getModifiedOn());
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
    }
    for (int i = 0; i < referenceIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, referenceIds_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (modifiedOn_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getModifiedOn());
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < referenceIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(referenceIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReferenceIdsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.rti.amanzi.protobuf.Origin)) {
      return super.equals(obj);
    }
    org.rti.amanzi.protobuf.Origin other = (org.rti.amanzi.protobuf.Origin) obj;

    if (hasModifiedOn() != other.hasModifiedOn()) return false;
    if (hasModifiedOn()) {
      if (!getModifiedOn()
          .equals(other.getModifiedOn())) return false;
    }
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getReferenceIdsList()
        .equals(other.getReferenceIdsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasModifiedOn()) {
      hash = (37 * hash) + MODIFIEDON_FIELD_NUMBER;
      hash = (53 * hash) + getModifiedOn().hashCode();
    }
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (getReferenceIdsCount() > 0) {
      hash = (37 * hash) + REFERENCEIDS_FIELD_NUMBER;
      hash = (53 * hash) + getReferenceIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.rti.amanzi.protobuf.Origin parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.Origin parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.Origin parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.Origin parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.Origin parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.Origin parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.Origin parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.Origin parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.Origin parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.Origin parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.Origin parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.Origin parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.rti.amanzi.protobuf.Origin prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rti.amanzi.protobuf.Origin}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rti.amanzi.protobuf.Origin)
      org.rti.amanzi.protobuf.OriginOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_Origin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_Origin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rti.amanzi.protobuf.Origin.class, org.rti.amanzi.protobuf.Origin.Builder.class);
    }

    // Construct using org.rti.amanzi.protobuf.Origin.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (modifiedOnBuilder_ == null) {
        modifiedOn_ = null;
      } else {
        modifiedOn_ = null;
        modifiedOnBuilder_ = null;
      }
      description_ = "";

      referenceIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_Origin_descriptor;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.Origin getDefaultInstanceForType() {
      return org.rti.amanzi.protobuf.Origin.getDefaultInstance();
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.Origin build() {
      org.rti.amanzi.protobuf.Origin result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.Origin buildPartial() {
      org.rti.amanzi.protobuf.Origin result = new org.rti.amanzi.protobuf.Origin(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (modifiedOnBuilder_ == null) {
        result.modifiedOn_ = modifiedOn_;
      } else {
        result.modifiedOn_ = modifiedOnBuilder_.build();
      }
      result.description_ = description_;
      if (((bitField0_ & 0x00000004) != 0)) {
        referenceIds_ = referenceIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.referenceIds_ = referenceIds_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.rti.amanzi.protobuf.Origin) {
        return mergeFrom((org.rti.amanzi.protobuf.Origin)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.rti.amanzi.protobuf.Origin other) {
      if (other == org.rti.amanzi.protobuf.Origin.getDefaultInstance()) return this;
      if (other.hasModifiedOn()) {
        mergeModifiedOn(other.getModifiedOn());
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.referenceIds_.isEmpty()) {
        if (referenceIds_.isEmpty()) {
          referenceIds_ = other.referenceIds_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureReferenceIdsIsMutable();
          referenceIds_.addAll(other.referenceIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.rti.amanzi.protobuf.Origin parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.rti.amanzi.protobuf.Origin) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.rti.amanzi.protobuf.Timestamp modifiedOn_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder> modifiedOnBuilder_;
    /**
     * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
     */
    public boolean hasModifiedOn() {
      return modifiedOnBuilder_ != null || modifiedOn_ != null;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
     */
    public org.rti.amanzi.protobuf.Timestamp getModifiedOn() {
      if (modifiedOnBuilder_ == null) {
        return modifiedOn_ == null ? org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : modifiedOn_;
      } else {
        return modifiedOnBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
     */
    public Builder setModifiedOn(org.rti.amanzi.protobuf.Timestamp value) {
      if (modifiedOnBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        modifiedOn_ = value;
        onChanged();
      } else {
        modifiedOnBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
     */
    public Builder setModifiedOn(
        org.rti.amanzi.protobuf.Timestamp.Builder builderForValue) {
      if (modifiedOnBuilder_ == null) {
        modifiedOn_ = builderForValue.build();
        onChanged();
      } else {
        modifiedOnBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
     */
    public Builder mergeModifiedOn(org.rti.amanzi.protobuf.Timestamp value) {
      if (modifiedOnBuilder_ == null) {
        if (modifiedOn_ != null) {
          modifiedOn_ =
            org.rti.amanzi.protobuf.Timestamp.newBuilder(modifiedOn_).mergeFrom(value).buildPartial();
        } else {
          modifiedOn_ = value;
        }
        onChanged();
      } else {
        modifiedOnBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
     */
    public Builder clearModifiedOn() {
      if (modifiedOnBuilder_ == null) {
        modifiedOn_ = null;
        onChanged();
      } else {
        modifiedOn_ = null;
        modifiedOnBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
     */
    public org.rti.amanzi.protobuf.Timestamp.Builder getModifiedOnBuilder() {
      
      onChanged();
      return getModifiedOnFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
     */
    public org.rti.amanzi.protobuf.TimestampOrBuilder getModifiedOnOrBuilder() {
      if (modifiedOnBuilder_ != null) {
        return modifiedOnBuilder_.getMessageOrBuilder();
      } else {
        return modifiedOn_ == null ?
            org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : modifiedOn_;
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder> 
        getModifiedOnFieldBuilder() {
      if (modifiedOnBuilder_ == null) {
        modifiedOnBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder>(
                getModifiedOn(),
                getParentForChildren(),
                isClean());
        modifiedOn_ = null;
      }
      return modifiedOnBuilder_;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 2;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList referenceIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureReferenceIdsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        referenceIds_ = new com.google.protobuf.LazyStringArrayList(referenceIds_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getReferenceIdsList() {
      return referenceIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    public int getReferenceIdsCount() {
      return referenceIds_.size();
    }
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    public java.lang.String getReferenceIds(int index) {
      return referenceIds_.get(index);
    }
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReferenceIdsBytes(int index) {
      return referenceIds_.getByteString(index);
    }
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    public Builder setReferenceIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReferenceIdsIsMutable();
      referenceIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    public Builder addReferenceIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReferenceIdsIsMutable();
      referenceIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    public Builder addAllReferenceIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureReferenceIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, referenceIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    public Builder clearReferenceIds() {
      referenceIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string referenceIds = 3;</code>
     */
    public Builder addReferenceIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureReferenceIdsIsMutable();
      referenceIds_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rti.amanzi.protobuf.Origin)
  }

  // @@protoc_insertion_point(class_scope:rti.amanzi.protobuf.Origin)
  private static final org.rti.amanzi.protobuf.Origin DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.rti.amanzi.protobuf.Origin();
  }

  public static org.rti.amanzi.protobuf.Origin getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Origin>
      PARSER = new com.google.protobuf.AbstractParser<Origin>() {
    @java.lang.Override
    public Origin parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Origin(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Origin> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Origin> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.rti.amanzi.protobuf.Origin getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

