// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

public interface OriginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti.amanzi.protobuf.Origin)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
   */
  boolean hasModifiedOn();
  /**
   * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
   */
  org.rti.amanzi.protobuf.Timestamp getModifiedOn();
  /**
   * <code>.rti.amanzi.protobuf.Timestamp modifiedOn = 1;</code>
   */
  org.rti.amanzi.protobuf.TimestampOrBuilder getModifiedOnOrBuilder();

  /**
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated string referenceIds = 3;</code>
   */
  java.util.List<java.lang.String>
      getReferenceIdsList();
  /**
   * <code>repeated string referenceIds = 3;</code>
   */
  int getReferenceIdsCount();
  /**
   * <code>repeated string referenceIds = 3;</code>
   */
  java.lang.String getReferenceIds(int index);
  /**
   * <code>repeated string referenceIds = 3;</code>
   */
  com.google.protobuf.ByteString
      getReferenceIdsBytes(int index);
}
