// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

public interface SourceLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti.amanzi.protobuf.SourceLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string code = 2;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
   */
  boolean hasElevation();
  /**
   * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
   */
  org.rti.amanzi.protobuf.Elevation getElevation();
  /**
   * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
   */
  org.rti.amanzi.protobuf.ElevationOrBuilder getElevationOrBuilder();
}
