// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

/**
 * Protobuf type {@code rti.amanzi.protobuf.SourceLocation}
 */
public  final class SourceLocation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rti.amanzi.protobuf.SourceLocation)
    SourceLocationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SourceLocation.newBuilder() to construct.
  private SourceLocation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SourceLocation() {
    name_ = "";
    code_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SourceLocation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            code_ = s;
            break;
          }
          case 26: {
            org.rti.amanzi.protobuf.Elevation.Builder subBuilder = null;
            if (elevation_ != null) {
              subBuilder = elevation_.toBuilder();
            }
            elevation_ = input.readMessage(org.rti.amanzi.protobuf.Elevation.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(elevation_);
              elevation_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_SourceLocation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_SourceLocation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.rti.amanzi.protobuf.SourceLocation.class, org.rti.amanzi.protobuf.SourceLocation.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object code_;
  /**
   * <code>string code = 2;</code>
   */
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <code>string code = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ELEVATION_FIELD_NUMBER = 3;
  private org.rti.amanzi.protobuf.Elevation elevation_;
  /**
   * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
   */
  public boolean hasElevation() {
    return elevation_ != null;
  }
  /**
   * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
   */
  public org.rti.amanzi.protobuf.Elevation getElevation() {
    return elevation_ == null ? org.rti.amanzi.protobuf.Elevation.getDefaultInstance() : elevation_;
  }
  /**
   * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
   */
  public org.rti.amanzi.protobuf.ElevationOrBuilder getElevationOrBuilder() {
    return getElevation();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
    }
    if (elevation_ != null) {
      output.writeMessage(3, getElevation());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
    }
    if (elevation_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getElevation());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.rti.amanzi.protobuf.SourceLocation)) {
      return super.equals(obj);
    }
    org.rti.amanzi.protobuf.SourceLocation other = (org.rti.amanzi.protobuf.SourceLocation) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getCode()
        .equals(other.getCode())) return false;
    if (hasElevation() != other.hasElevation()) return false;
    if (hasElevation()) {
      if (!getElevation()
          .equals(other.getElevation())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    if (hasElevation()) {
      hash = (37 * hash) + ELEVATION_FIELD_NUMBER;
      hash = (53 * hash) + getElevation().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.rti.amanzi.protobuf.SourceLocation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.SourceLocation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.SourceLocation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.SourceLocation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.SourceLocation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.SourceLocation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.SourceLocation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.SourceLocation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.SourceLocation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.SourceLocation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.SourceLocation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.SourceLocation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.rti.amanzi.protobuf.SourceLocation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rti.amanzi.protobuf.SourceLocation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rti.amanzi.protobuf.SourceLocation)
      org.rti.amanzi.protobuf.SourceLocationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_SourceLocation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_SourceLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rti.amanzi.protobuf.SourceLocation.class, org.rti.amanzi.protobuf.SourceLocation.Builder.class);
    }

    // Construct using org.rti.amanzi.protobuf.SourceLocation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      code_ = "";

      if (elevationBuilder_ == null) {
        elevation_ = null;
      } else {
        elevation_ = null;
        elevationBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_SourceLocation_descriptor;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.SourceLocation getDefaultInstanceForType() {
      return org.rti.amanzi.protobuf.SourceLocation.getDefaultInstance();
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.SourceLocation build() {
      org.rti.amanzi.protobuf.SourceLocation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.SourceLocation buildPartial() {
      org.rti.amanzi.protobuf.SourceLocation result = new org.rti.amanzi.protobuf.SourceLocation(this);
      result.name_ = name_;
      result.code_ = code_;
      if (elevationBuilder_ == null) {
        result.elevation_ = elevation_;
      } else {
        result.elevation_ = elevationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.rti.amanzi.protobuf.SourceLocation) {
        return mergeFrom((org.rti.amanzi.protobuf.SourceLocation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.rti.amanzi.protobuf.SourceLocation other) {
      if (other == org.rti.amanzi.protobuf.SourceLocation.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        onChanged();
      }
      if (other.hasElevation()) {
        mergeElevation(other.getElevation());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.rti.amanzi.protobuf.SourceLocation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.rti.amanzi.protobuf.SourceLocation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object code_ = "";
    /**
     * <code>string code = 2;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string code = 2;</code>
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string code = 2;</code>
     */
    public Builder clearCode() {
      
      code_ = getDefaultInstance().getCode();
      onChanged();
      return this;
    }
    /**
     * <code>string code = 2;</code>
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      code_ = value;
      onChanged();
      return this;
    }

    private org.rti.amanzi.protobuf.Elevation elevation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Elevation, org.rti.amanzi.protobuf.Elevation.Builder, org.rti.amanzi.protobuf.ElevationOrBuilder> elevationBuilder_;
    /**
     * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
     */
    public boolean hasElevation() {
      return elevationBuilder_ != null || elevation_ != null;
    }
    /**
     * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
     */
    public org.rti.amanzi.protobuf.Elevation getElevation() {
      if (elevationBuilder_ == null) {
        return elevation_ == null ? org.rti.amanzi.protobuf.Elevation.getDefaultInstance() : elevation_;
      } else {
        return elevationBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
     */
    public Builder setElevation(org.rti.amanzi.protobuf.Elevation value) {
      if (elevationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        elevation_ = value;
        onChanged();
      } else {
        elevationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
     */
    public Builder setElevation(
        org.rti.amanzi.protobuf.Elevation.Builder builderForValue) {
      if (elevationBuilder_ == null) {
        elevation_ = builderForValue.build();
        onChanged();
      } else {
        elevationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
     */
    public Builder mergeElevation(org.rti.amanzi.protobuf.Elevation value) {
      if (elevationBuilder_ == null) {
        if (elevation_ != null) {
          elevation_ =
            org.rti.amanzi.protobuf.Elevation.newBuilder(elevation_).mergeFrom(value).buildPartial();
        } else {
          elevation_ = value;
        }
        onChanged();
      } else {
        elevationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
     */
    public Builder clearElevation() {
      if (elevationBuilder_ == null) {
        elevation_ = null;
        onChanged();
      } else {
        elevation_ = null;
        elevationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
     */
    public org.rti.amanzi.protobuf.Elevation.Builder getElevationBuilder() {
      
      onChanged();
      return getElevationFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
     */
    public org.rti.amanzi.protobuf.ElevationOrBuilder getElevationOrBuilder() {
      if (elevationBuilder_ != null) {
        return elevationBuilder_.getMessageOrBuilder();
      } else {
        return elevation_ == null ?
            org.rti.amanzi.protobuf.Elevation.getDefaultInstance() : elevation_;
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Elevation elevation = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Elevation, org.rti.amanzi.protobuf.Elevation.Builder, org.rti.amanzi.protobuf.ElevationOrBuilder> 
        getElevationFieldBuilder() {
      if (elevationBuilder_ == null) {
        elevationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.rti.amanzi.protobuf.Elevation, org.rti.amanzi.protobuf.Elevation.Builder, org.rti.amanzi.protobuf.ElevationOrBuilder>(
                getElevation(),
                getParentForChildren(),
                isClean());
        elevation_ = null;
      }
      return elevationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rti.amanzi.protobuf.SourceLocation)
  }

  // @@protoc_insertion_point(class_scope:rti.amanzi.protobuf.SourceLocation)
  private static final org.rti.amanzi.protobuf.SourceLocation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.rti.amanzi.protobuf.SourceLocation();
  }

  public static org.rti.amanzi.protobuf.SourceLocation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SourceLocation>
      PARSER = new com.google.protobuf.AbstractParser<SourceLocation>() {
    @java.lang.Override
    public SourceLocation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SourceLocation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SourceLocation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SourceLocation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.rti.amanzi.protobuf.SourceLocation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

