// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

public interface StructOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti.amanzi.protobuf.Struct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unordered map of dynamically typed values.
   * </pre>
   *
   * <code>map&lt;string, .rti.amanzi.protobuf.Value&gt; fields = 1;</code>
   */
  int getFieldsCount();
  /**
   * <pre>
   * Unordered map of dynamically typed values.
   * </pre>
   *
   * <code>map&lt;string, .rti.amanzi.protobuf.Value&gt; fields = 1;</code>
   */
  boolean containsFields(
      java.lang.String key);
  /**
   * Use {@link #getFieldsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.rti.amanzi.protobuf.Value>
  getFields();
  /**
   * <pre>
   * Unordered map of dynamically typed values.
   * </pre>
   *
   * <code>map&lt;string, .rti.amanzi.protobuf.Value&gt; fields = 1;</code>
   */
  java.util.Map<java.lang.String, org.rti.amanzi.protobuf.Value>
  getFieldsMap();
  /**
   * <pre>
   * Unordered map of dynamically typed values.
   * </pre>
   *
   * <code>map&lt;string, .rti.amanzi.protobuf.Value&gt; fields = 1;</code>
   */

  org.rti.amanzi.protobuf.Value getFieldsOrDefault(
      java.lang.String key,
      org.rti.amanzi.protobuf.Value defaultValue);
  /**
   * <pre>
   * Unordered map of dynamically typed values.
   * </pre>
   *
   * <code>map&lt;string, .rti.amanzi.protobuf.Value&gt; fields = 1;</code>
   */

  org.rti.amanzi.protobuf.Value getFieldsOrThrow(
      java.lang.String key);
}
