// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

public interface TimeRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti.amanzi.protobuf.TimeRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
   */
  boolean hasDatetime();
  /**
   * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
   */
  org.rti.amanzi.protobuf.Timestamp getDatetime();
  /**
   * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
   */
  org.rti.amanzi.protobuf.TimestampOrBuilder getDatetimeOrBuilder();

  /**
   * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
   */
  boolean hasValue();
  /**
   * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
   */
  org.rti.amanzi.protobuf.NumberValue getValue();
  /**
   * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
   */
  org.rti.amanzi.protobuf.NumberValueOrBuilder getValueOrBuilder();

  /**
   * <code>repeated string qualifiers = 3;</code>
   */
  java.util.List<java.lang.String>
      getQualifiersList();
  /**
   * <code>repeated string qualifiers = 3;</code>
   */
  int getQualifiersCount();
  /**
   * <code>repeated string qualifiers = 3;</code>
   */
  java.lang.String getQualifiers(int index);
  /**
   * <code>repeated string qualifiers = 3;</code>
   */
  com.google.protobuf.ByteString
      getQualifiersBytes(int index);

  /**
   * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
   */
  boolean hasProperties();
  /**
   * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
   */
  org.rti.amanzi.protobuf.Struct getProperties();
  /**
   * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
   */
  org.rti.amanzi.protobuf.StructOrBuilder getPropertiesOrBuilder();
}
