// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

/**
 * Protobuf type {@code rti.amanzi.protobuf.TimeInfo}
 */
public  final class TimeInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rti.amanzi.protobuf.TimeInfo)
    TimeInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TimeInfo.newBuilder() to construct.
  private TimeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TimeInfo() {
    interval_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TimeInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.rti.amanzi.protobuf.Timestamp.Builder subBuilder = null;
            if (referenceTime_ != null) {
              subBuilder = referenceTime_.toBuilder();
            }
            referenceTime_ = input.readMessage(org.rti.amanzi.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(referenceTime_);
              referenceTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.rti.amanzi.protobuf.Timestamp.Builder subBuilder = null;
            if (start_ != null) {
              subBuilder = start_.toBuilder();
            }
            start_ = input.readMessage(org.rti.amanzi.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(start_);
              start_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            org.rti.amanzi.protobuf.Timestamp.Builder subBuilder = null;
            if (end_ != null) {
              subBuilder = end_.toBuilder();
            }
            end_ = input.readMessage(org.rti.amanzi.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(end_);
              end_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            interval_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.rti.amanzi.protobuf.TimeInfo.class, org.rti.amanzi.protobuf.TimeInfo.Builder.class);
  }

  public static final int REFERENCETIME_FIELD_NUMBER = 1;
  private org.rti.amanzi.protobuf.Timestamp referenceTime_;
  /**
   * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
   */
  public boolean hasReferenceTime() {
    return referenceTime_ != null;
  }
  /**
   * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
   */
  public org.rti.amanzi.protobuf.Timestamp getReferenceTime() {
    return referenceTime_ == null ? org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : referenceTime_;
  }
  /**
   * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
   */
  public org.rti.amanzi.protobuf.TimestampOrBuilder getReferenceTimeOrBuilder() {
    return getReferenceTime();
  }

  public static final int START_FIELD_NUMBER = 2;
  private org.rti.amanzi.protobuf.Timestamp start_;
  /**
   * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
   */
  public boolean hasStart() {
    return start_ != null;
  }
  /**
   * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
   */
  public org.rti.amanzi.protobuf.Timestamp getStart() {
    return start_ == null ? org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : start_;
  }
  /**
   * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
   */
  public org.rti.amanzi.protobuf.TimestampOrBuilder getStartOrBuilder() {
    return getStart();
  }

  public static final int END_FIELD_NUMBER = 3;
  private org.rti.amanzi.protobuf.Timestamp end_;
  /**
   * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
   */
  public boolean hasEnd() {
    return end_ != null;
  }
  /**
   * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
   */
  public org.rti.amanzi.protobuf.Timestamp getEnd() {
    return end_ == null ? org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : end_;
  }
  /**
   * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
   */
  public org.rti.amanzi.protobuf.TimestampOrBuilder getEndOrBuilder() {
    return getEnd();
  }

  public static final int INTERVAL_FIELD_NUMBER = 4;
  private volatile java.lang.Object interval_;
  /**
   * <code>string interval = 4;</code>
   */
  public java.lang.String getInterval() {
    java.lang.Object ref = interval_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      interval_ = s;
      return s;
    }
  }
  /**
   * <code>string interval = 4;</code>
   */
  public com.google.protobuf.ByteString
      getIntervalBytes() {
    java.lang.Object ref = interval_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      interval_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (referenceTime_ != null) {
      output.writeMessage(1, getReferenceTime());
    }
    if (start_ != null) {
      output.writeMessage(2, getStart());
    }
    if (end_ != null) {
      output.writeMessage(3, getEnd());
    }
    if (!getIntervalBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, interval_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (referenceTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getReferenceTime());
    }
    if (start_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStart());
    }
    if (end_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getEnd());
    }
    if (!getIntervalBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, interval_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.rti.amanzi.protobuf.TimeInfo)) {
      return super.equals(obj);
    }
    org.rti.amanzi.protobuf.TimeInfo other = (org.rti.amanzi.protobuf.TimeInfo) obj;

    if (hasReferenceTime() != other.hasReferenceTime()) return false;
    if (hasReferenceTime()) {
      if (!getReferenceTime()
          .equals(other.getReferenceTime())) return false;
    }
    if (hasStart() != other.hasStart()) return false;
    if (hasStart()) {
      if (!getStart()
          .equals(other.getStart())) return false;
    }
    if (hasEnd() != other.hasEnd()) return false;
    if (hasEnd()) {
      if (!getEnd()
          .equals(other.getEnd())) return false;
    }
    if (!getInterval()
        .equals(other.getInterval())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasReferenceTime()) {
      hash = (37 * hash) + REFERENCETIME_FIELD_NUMBER;
      hash = (53 * hash) + getReferenceTime().hashCode();
    }
    if (hasStart()) {
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + getStart().hashCode();
    }
    if (hasEnd()) {
      hash = (37 * hash) + END_FIELD_NUMBER;
      hash = (53 * hash) + getEnd().hashCode();
    }
    hash = (37 * hash) + INTERVAL_FIELD_NUMBER;
    hash = (53 * hash) + getInterval().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.rti.amanzi.protobuf.TimeInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.TimeInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.TimeInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.TimeInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.TimeInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.TimeInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.TimeInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.rti.amanzi.protobuf.TimeInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rti.amanzi.protobuf.TimeInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rti.amanzi.protobuf.TimeInfo)
      org.rti.amanzi.protobuf.TimeInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rti.amanzi.protobuf.TimeInfo.class, org.rti.amanzi.protobuf.TimeInfo.Builder.class);
    }

    // Construct using org.rti.amanzi.protobuf.TimeInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (referenceTimeBuilder_ == null) {
        referenceTime_ = null;
      } else {
        referenceTime_ = null;
        referenceTimeBuilder_ = null;
      }
      if (startBuilder_ == null) {
        start_ = null;
      } else {
        start_ = null;
        startBuilder_ = null;
      }
      if (endBuilder_ == null) {
        end_ = null;
      } else {
        end_ = null;
        endBuilder_ = null;
      }
      interval_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeInfo_descriptor;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.TimeInfo getDefaultInstanceForType() {
      return org.rti.amanzi.protobuf.TimeInfo.getDefaultInstance();
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.TimeInfo build() {
      org.rti.amanzi.protobuf.TimeInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.TimeInfo buildPartial() {
      org.rti.amanzi.protobuf.TimeInfo result = new org.rti.amanzi.protobuf.TimeInfo(this);
      if (referenceTimeBuilder_ == null) {
        result.referenceTime_ = referenceTime_;
      } else {
        result.referenceTime_ = referenceTimeBuilder_.build();
      }
      if (startBuilder_ == null) {
        result.start_ = start_;
      } else {
        result.start_ = startBuilder_.build();
      }
      if (endBuilder_ == null) {
        result.end_ = end_;
      } else {
        result.end_ = endBuilder_.build();
      }
      result.interval_ = interval_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.rti.amanzi.protobuf.TimeInfo) {
        return mergeFrom((org.rti.amanzi.protobuf.TimeInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.rti.amanzi.protobuf.TimeInfo other) {
      if (other == org.rti.amanzi.protobuf.TimeInfo.getDefaultInstance()) return this;
      if (other.hasReferenceTime()) {
        mergeReferenceTime(other.getReferenceTime());
      }
      if (other.hasStart()) {
        mergeStart(other.getStart());
      }
      if (other.hasEnd()) {
        mergeEnd(other.getEnd());
      }
      if (!other.getInterval().isEmpty()) {
        interval_ = other.interval_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.rti.amanzi.protobuf.TimeInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.rti.amanzi.protobuf.TimeInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.rti.amanzi.protobuf.Timestamp referenceTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder> referenceTimeBuilder_;
    /**
     * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
     */
    public boolean hasReferenceTime() {
      return referenceTimeBuilder_ != null || referenceTime_ != null;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
     */
    public org.rti.amanzi.protobuf.Timestamp getReferenceTime() {
      if (referenceTimeBuilder_ == null) {
        return referenceTime_ == null ? org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : referenceTime_;
      } else {
        return referenceTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
     */
    public Builder setReferenceTime(org.rti.amanzi.protobuf.Timestamp value) {
      if (referenceTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        referenceTime_ = value;
        onChanged();
      } else {
        referenceTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
     */
    public Builder setReferenceTime(
        org.rti.amanzi.protobuf.Timestamp.Builder builderForValue) {
      if (referenceTimeBuilder_ == null) {
        referenceTime_ = builderForValue.build();
        onChanged();
      } else {
        referenceTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
     */
    public Builder mergeReferenceTime(org.rti.amanzi.protobuf.Timestamp value) {
      if (referenceTimeBuilder_ == null) {
        if (referenceTime_ != null) {
          referenceTime_ =
            org.rti.amanzi.protobuf.Timestamp.newBuilder(referenceTime_).mergeFrom(value).buildPartial();
        } else {
          referenceTime_ = value;
        }
        onChanged();
      } else {
        referenceTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
     */
    public Builder clearReferenceTime() {
      if (referenceTimeBuilder_ == null) {
        referenceTime_ = null;
        onChanged();
      } else {
        referenceTime_ = null;
        referenceTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
     */
    public org.rti.amanzi.protobuf.Timestamp.Builder getReferenceTimeBuilder() {
      
      onChanged();
      return getReferenceTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
     */
    public org.rti.amanzi.protobuf.TimestampOrBuilder getReferenceTimeOrBuilder() {
      if (referenceTimeBuilder_ != null) {
        return referenceTimeBuilder_.getMessageOrBuilder();
      } else {
        return referenceTime_ == null ?
            org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : referenceTime_;
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder> 
        getReferenceTimeFieldBuilder() {
      if (referenceTimeBuilder_ == null) {
        referenceTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder>(
                getReferenceTime(),
                getParentForChildren(),
                isClean());
        referenceTime_ = null;
      }
      return referenceTimeBuilder_;
    }

    private org.rti.amanzi.protobuf.Timestamp start_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder> startBuilder_;
    /**
     * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
     */
    public boolean hasStart() {
      return startBuilder_ != null || start_ != null;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
     */
    public org.rti.amanzi.protobuf.Timestamp getStart() {
      if (startBuilder_ == null) {
        return start_ == null ? org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : start_;
      } else {
        return startBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
     */
    public Builder setStart(org.rti.amanzi.protobuf.Timestamp value) {
      if (startBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        start_ = value;
        onChanged();
      } else {
        startBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
     */
    public Builder setStart(
        org.rti.amanzi.protobuf.Timestamp.Builder builderForValue) {
      if (startBuilder_ == null) {
        start_ = builderForValue.build();
        onChanged();
      } else {
        startBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
     */
    public Builder mergeStart(org.rti.amanzi.protobuf.Timestamp value) {
      if (startBuilder_ == null) {
        if (start_ != null) {
          start_ =
            org.rti.amanzi.protobuf.Timestamp.newBuilder(start_).mergeFrom(value).buildPartial();
        } else {
          start_ = value;
        }
        onChanged();
      } else {
        startBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
     */
    public Builder clearStart() {
      if (startBuilder_ == null) {
        start_ = null;
        onChanged();
      } else {
        start_ = null;
        startBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
     */
    public org.rti.amanzi.protobuf.Timestamp.Builder getStartBuilder() {
      
      onChanged();
      return getStartFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
     */
    public org.rti.amanzi.protobuf.TimestampOrBuilder getStartOrBuilder() {
      if (startBuilder_ != null) {
        return startBuilder_.getMessageOrBuilder();
      } else {
        return start_ == null ?
            org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : start_;
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder> 
        getStartFieldBuilder() {
      if (startBuilder_ == null) {
        startBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder>(
                getStart(),
                getParentForChildren(),
                isClean());
        start_ = null;
      }
      return startBuilder_;
    }

    private org.rti.amanzi.protobuf.Timestamp end_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder> endBuilder_;
    /**
     * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
     */
    public boolean hasEnd() {
      return endBuilder_ != null || end_ != null;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
     */
    public org.rti.amanzi.protobuf.Timestamp getEnd() {
      if (endBuilder_ == null) {
        return end_ == null ? org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : end_;
      } else {
        return endBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
     */
    public Builder setEnd(org.rti.amanzi.protobuf.Timestamp value) {
      if (endBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        end_ = value;
        onChanged();
      } else {
        endBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
     */
    public Builder setEnd(
        org.rti.amanzi.protobuf.Timestamp.Builder builderForValue) {
      if (endBuilder_ == null) {
        end_ = builderForValue.build();
        onChanged();
      } else {
        endBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
     */
    public Builder mergeEnd(org.rti.amanzi.protobuf.Timestamp value) {
      if (endBuilder_ == null) {
        if (end_ != null) {
          end_ =
            org.rti.amanzi.protobuf.Timestamp.newBuilder(end_).mergeFrom(value).buildPartial();
        } else {
          end_ = value;
        }
        onChanged();
      } else {
        endBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
     */
    public Builder clearEnd() {
      if (endBuilder_ == null) {
        end_ = null;
        onChanged();
      } else {
        end_ = null;
        endBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
     */
    public org.rti.amanzi.protobuf.Timestamp.Builder getEndBuilder() {
      
      onChanged();
      return getEndFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
     */
    public org.rti.amanzi.protobuf.TimestampOrBuilder getEndOrBuilder() {
      if (endBuilder_ != null) {
        return endBuilder_.getMessageOrBuilder();
      } else {
        return end_ == null ?
            org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : end_;
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder> 
        getEndFieldBuilder() {
      if (endBuilder_ == null) {
        endBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder>(
                getEnd(),
                getParentForChildren(),
                isClean());
        end_ = null;
      }
      return endBuilder_;
    }

    private java.lang.Object interval_ = "";
    /**
     * <code>string interval = 4;</code>
     */
    public java.lang.String getInterval() {
      java.lang.Object ref = interval_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interval_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string interval = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIntervalBytes() {
      java.lang.Object ref = interval_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interval_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string interval = 4;</code>
     */
    public Builder setInterval(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      interval_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string interval = 4;</code>
     */
    public Builder clearInterval() {
      
      interval_ = getDefaultInstance().getInterval();
      onChanged();
      return this;
    }
    /**
     * <code>string interval = 4;</code>
     */
    public Builder setIntervalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      interval_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rti.amanzi.protobuf.TimeInfo)
  }

  // @@protoc_insertion_point(class_scope:rti.amanzi.protobuf.TimeInfo)
  private static final org.rti.amanzi.protobuf.TimeInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.rti.amanzi.protobuf.TimeInfo();
  }

  public static org.rti.amanzi.protobuf.TimeInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TimeInfo>
      PARSER = new com.google.protobuf.AbstractParser<TimeInfo>() {
    @java.lang.Override
    public TimeInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TimeInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TimeInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TimeInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.rti.amanzi.protobuf.TimeInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

