// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

public interface TimeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti.amanzi.protobuf.TimeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
   */
  boolean hasReferenceTime();
  /**
   * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
   */
  org.rti.amanzi.protobuf.Timestamp getReferenceTime();
  /**
   * <code>.rti.amanzi.protobuf.Timestamp referenceTime = 1;</code>
   */
  org.rti.amanzi.protobuf.TimestampOrBuilder getReferenceTimeOrBuilder();

  /**
   * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
   */
  boolean hasStart();
  /**
   * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
   */
  org.rti.amanzi.protobuf.Timestamp getStart();
  /**
   * <code>.rti.amanzi.protobuf.Timestamp start = 2;</code>
   */
  org.rti.amanzi.protobuf.TimestampOrBuilder getStartOrBuilder();

  /**
   * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
   */
  boolean hasEnd();
  /**
   * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
   */
  org.rti.amanzi.protobuf.Timestamp getEnd();
  /**
   * <code>.rti.amanzi.protobuf.Timestamp end = 3;</code>
   */
  org.rti.amanzi.protobuf.TimestampOrBuilder getEndOrBuilder();

  /**
   * <code>string interval = 4;</code>
   */
  java.lang.String getInterval();
  /**
   * <code>string interval = 4;</code>
   */
  com.google.protobuf.ByteString
      getIntervalBytes();
}
