// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

/**
 * Protobuf type {@code rti.amanzi.protobuf.TimeRecord}
 */
public  final class TimeRecord extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rti.amanzi.protobuf.TimeRecord)
    TimeRecordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TimeRecord.newBuilder() to construct.
  private TimeRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TimeRecord() {
    qualifiers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TimeRecord(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.rti.amanzi.protobuf.Timestamp.Builder subBuilder = null;
            if (datetime_ != null) {
              subBuilder = datetime_.toBuilder();
            }
            datetime_ = input.readMessage(org.rti.amanzi.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(datetime_);
              datetime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.rti.amanzi.protobuf.NumberValue.Builder subBuilder = null;
            if (value_ != null) {
              subBuilder = value_.toBuilder();
            }
            value_ = input.readMessage(org.rti.amanzi.protobuf.NumberValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(value_);
              value_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              qualifiers_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            qualifiers_.add(s);
            break;
          }
          case 34: {
            org.rti.amanzi.protobuf.Struct.Builder subBuilder = null;
            if (properties_ != null) {
              subBuilder = properties_.toBuilder();
            }
            properties_ = input.readMessage(org.rti.amanzi.protobuf.Struct.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(properties_);
              properties_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        qualifiers_ = qualifiers_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeRecord_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.rti.amanzi.protobuf.TimeRecord.class, org.rti.amanzi.protobuf.TimeRecord.Builder.class);
  }

  private int bitField0_;
  public static final int DATETIME_FIELD_NUMBER = 1;
  private org.rti.amanzi.protobuf.Timestamp datetime_;
  /**
   * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
   */
  public boolean hasDatetime() {
    return datetime_ != null;
  }
  /**
   * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
   */
  public org.rti.amanzi.protobuf.Timestamp getDatetime() {
    return datetime_ == null ? org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : datetime_;
  }
  /**
   * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
   */
  public org.rti.amanzi.protobuf.TimestampOrBuilder getDatetimeOrBuilder() {
    return getDatetime();
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private org.rti.amanzi.protobuf.NumberValue value_;
  /**
   * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
   */
  public boolean hasValue() {
    return value_ != null;
  }
  /**
   * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
   */
  public org.rti.amanzi.protobuf.NumberValue getValue() {
    return value_ == null ? org.rti.amanzi.protobuf.NumberValue.getDefaultInstance() : value_;
  }
  /**
   * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
   */
  public org.rti.amanzi.protobuf.NumberValueOrBuilder getValueOrBuilder() {
    return getValue();
  }

  public static final int QUALIFIERS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList qualifiers_;
  /**
   * <code>repeated string qualifiers = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getQualifiersList() {
    return qualifiers_;
  }
  /**
   * <code>repeated string qualifiers = 3;</code>
   */
  public int getQualifiersCount() {
    return qualifiers_.size();
  }
  /**
   * <code>repeated string qualifiers = 3;</code>
   */
  public java.lang.String getQualifiers(int index) {
    return qualifiers_.get(index);
  }
  /**
   * <code>repeated string qualifiers = 3;</code>
   */
  public com.google.protobuf.ByteString
      getQualifiersBytes(int index) {
    return qualifiers_.getByteString(index);
  }

  public static final int PROPERTIES_FIELD_NUMBER = 4;
  private org.rti.amanzi.protobuf.Struct properties_;
  /**
   * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
   */
  public boolean hasProperties() {
    return properties_ != null;
  }
  /**
   * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
   */
  public org.rti.amanzi.protobuf.Struct getProperties() {
    return properties_ == null ? org.rti.amanzi.protobuf.Struct.getDefaultInstance() : properties_;
  }
  /**
   * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
   */
  public org.rti.amanzi.protobuf.StructOrBuilder getPropertiesOrBuilder() {
    return getProperties();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (datetime_ != null) {
      output.writeMessage(1, getDatetime());
    }
    if (value_ != null) {
      output.writeMessage(2, getValue());
    }
    for (int i = 0; i < qualifiers_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, qualifiers_.getRaw(i));
    }
    if (properties_ != null) {
      output.writeMessage(4, getProperties());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (datetime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDatetime());
    }
    if (value_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getValue());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < qualifiers_.size(); i++) {
        dataSize += computeStringSizeNoTag(qualifiers_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getQualifiersList().size();
    }
    if (properties_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getProperties());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.rti.amanzi.protobuf.TimeRecord)) {
      return super.equals(obj);
    }
    org.rti.amanzi.protobuf.TimeRecord other = (org.rti.amanzi.protobuf.TimeRecord) obj;

    if (hasDatetime() != other.hasDatetime()) return false;
    if (hasDatetime()) {
      if (!getDatetime()
          .equals(other.getDatetime())) return false;
    }
    if (hasValue() != other.hasValue()) return false;
    if (hasValue()) {
      if (!getValue()
          .equals(other.getValue())) return false;
    }
    if (!getQualifiersList()
        .equals(other.getQualifiersList())) return false;
    if (hasProperties() != other.hasProperties()) return false;
    if (hasProperties()) {
      if (!getProperties()
          .equals(other.getProperties())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDatetime()) {
      hash = (37 * hash) + DATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getDatetime().hashCode();
    }
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    if (getQualifiersCount() > 0) {
      hash = (37 * hash) + QUALIFIERS_FIELD_NUMBER;
      hash = (53 * hash) + getQualifiersList().hashCode();
    }
    if (hasProperties()) {
      hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
      hash = (53 * hash) + getProperties().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.rti.amanzi.protobuf.TimeRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.TimeRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.TimeRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.TimeRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.TimeRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.TimeRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.TimeRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.rti.amanzi.protobuf.TimeRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rti.amanzi.protobuf.TimeRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rti.amanzi.protobuf.TimeRecord)
      org.rti.amanzi.protobuf.TimeRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rti.amanzi.protobuf.TimeRecord.class, org.rti.amanzi.protobuf.TimeRecord.Builder.class);
    }

    // Construct using org.rti.amanzi.protobuf.TimeRecord.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (datetimeBuilder_ == null) {
        datetime_ = null;
      } else {
        datetime_ = null;
        datetimeBuilder_ = null;
      }
      if (valueBuilder_ == null) {
        value_ = null;
      } else {
        value_ = null;
        valueBuilder_ = null;
      }
      qualifiers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (propertiesBuilder_ == null) {
        properties_ = null;
      } else {
        properties_ = null;
        propertiesBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeRecord_descriptor;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.TimeRecord getDefaultInstanceForType() {
      return org.rti.amanzi.protobuf.TimeRecord.getDefaultInstance();
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.TimeRecord build() {
      org.rti.amanzi.protobuf.TimeRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.TimeRecord buildPartial() {
      org.rti.amanzi.protobuf.TimeRecord result = new org.rti.amanzi.protobuf.TimeRecord(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (datetimeBuilder_ == null) {
        result.datetime_ = datetime_;
      } else {
        result.datetime_ = datetimeBuilder_.build();
      }
      if (valueBuilder_ == null) {
        result.value_ = value_;
      } else {
        result.value_ = valueBuilder_.build();
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        qualifiers_ = qualifiers_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.qualifiers_ = qualifiers_;
      if (propertiesBuilder_ == null) {
        result.properties_ = properties_;
      } else {
        result.properties_ = propertiesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.rti.amanzi.protobuf.TimeRecord) {
        return mergeFrom((org.rti.amanzi.protobuf.TimeRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.rti.amanzi.protobuf.TimeRecord other) {
      if (other == org.rti.amanzi.protobuf.TimeRecord.getDefaultInstance()) return this;
      if (other.hasDatetime()) {
        mergeDatetime(other.getDatetime());
      }
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      if (!other.qualifiers_.isEmpty()) {
        if (qualifiers_.isEmpty()) {
          qualifiers_ = other.qualifiers_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureQualifiersIsMutable();
          qualifiers_.addAll(other.qualifiers_);
        }
        onChanged();
      }
      if (other.hasProperties()) {
        mergeProperties(other.getProperties());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.rti.amanzi.protobuf.TimeRecord parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.rti.amanzi.protobuf.TimeRecord) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.rti.amanzi.protobuf.Timestamp datetime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder> datetimeBuilder_;
    /**
     * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
     */
    public boolean hasDatetime() {
      return datetimeBuilder_ != null || datetime_ != null;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
     */
    public org.rti.amanzi.protobuf.Timestamp getDatetime() {
      if (datetimeBuilder_ == null) {
        return datetime_ == null ? org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : datetime_;
      } else {
        return datetimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
     */
    public Builder setDatetime(org.rti.amanzi.protobuf.Timestamp value) {
      if (datetimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        datetime_ = value;
        onChanged();
      } else {
        datetimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
     */
    public Builder setDatetime(
        org.rti.amanzi.protobuf.Timestamp.Builder builderForValue) {
      if (datetimeBuilder_ == null) {
        datetime_ = builderForValue.build();
        onChanged();
      } else {
        datetimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
     */
    public Builder mergeDatetime(org.rti.amanzi.protobuf.Timestamp value) {
      if (datetimeBuilder_ == null) {
        if (datetime_ != null) {
          datetime_ =
            org.rti.amanzi.protobuf.Timestamp.newBuilder(datetime_).mergeFrom(value).buildPartial();
        } else {
          datetime_ = value;
        }
        onChanged();
      } else {
        datetimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
     */
    public Builder clearDatetime() {
      if (datetimeBuilder_ == null) {
        datetime_ = null;
        onChanged();
      } else {
        datetime_ = null;
        datetimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
     */
    public org.rti.amanzi.protobuf.Timestamp.Builder getDatetimeBuilder() {
      
      onChanged();
      return getDatetimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
     */
    public org.rti.amanzi.protobuf.TimestampOrBuilder getDatetimeOrBuilder() {
      if (datetimeBuilder_ != null) {
        return datetimeBuilder_.getMessageOrBuilder();
      } else {
        return datetime_ == null ?
            org.rti.amanzi.protobuf.Timestamp.getDefaultInstance() : datetime_;
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Timestamp datetime = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder> 
        getDatetimeFieldBuilder() {
      if (datetimeBuilder_ == null) {
        datetimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.rti.amanzi.protobuf.Timestamp, org.rti.amanzi.protobuf.Timestamp.Builder, org.rti.amanzi.protobuf.TimestampOrBuilder>(
                getDatetime(),
                getParentForChildren(),
                isClean());
        datetime_ = null;
      }
      return datetimeBuilder_;
    }

    private org.rti.amanzi.protobuf.NumberValue value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.NumberValue, org.rti.amanzi.protobuf.NumberValue.Builder, org.rti.amanzi.protobuf.NumberValueOrBuilder> valueBuilder_;
    /**
     * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
     */
    public boolean hasValue() {
      return valueBuilder_ != null || value_ != null;
    }
    /**
     * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
     */
    public org.rti.amanzi.protobuf.NumberValue getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? org.rti.amanzi.protobuf.NumberValue.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
     */
    public Builder setValue(org.rti.amanzi.protobuf.NumberValue value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        valueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
     */
    public Builder setValue(
        org.rti.amanzi.protobuf.NumberValue.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
     */
    public Builder mergeValue(org.rti.amanzi.protobuf.NumberValue value) {
      if (valueBuilder_ == null) {
        if (value_ != null) {
          value_ =
            org.rti.amanzi.protobuf.NumberValue.newBuilder(value_).mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        valueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
     */
    public Builder clearValue() {
      if (valueBuilder_ == null) {
        value_ = null;
        onChanged();
      } else {
        value_ = null;
        valueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
     */
    public org.rti.amanzi.protobuf.NumberValue.Builder getValueBuilder() {
      
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
     */
    public org.rti.amanzi.protobuf.NumberValueOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            org.rti.amanzi.protobuf.NumberValue.getDefaultInstance() : value_;
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.NumberValue value = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.NumberValue, org.rti.amanzi.protobuf.NumberValue.Builder, org.rti.amanzi.protobuf.NumberValueOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.rti.amanzi.protobuf.NumberValue, org.rti.amanzi.protobuf.NumberValue.Builder, org.rti.amanzi.protobuf.NumberValueOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }

    private com.google.protobuf.LazyStringList qualifiers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureQualifiersIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        qualifiers_ = new com.google.protobuf.LazyStringArrayList(qualifiers_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string qualifiers = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getQualifiersList() {
      return qualifiers_.getUnmodifiableView();
    }
    /**
     * <code>repeated string qualifiers = 3;</code>
     */
    public int getQualifiersCount() {
      return qualifiers_.size();
    }
    /**
     * <code>repeated string qualifiers = 3;</code>
     */
    public java.lang.String getQualifiers(int index) {
      return qualifiers_.get(index);
    }
    /**
     * <code>repeated string qualifiers = 3;</code>
     */
    public com.google.protobuf.ByteString
        getQualifiersBytes(int index) {
      return qualifiers_.getByteString(index);
    }
    /**
     * <code>repeated string qualifiers = 3;</code>
     */
    public Builder setQualifiers(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureQualifiersIsMutable();
      qualifiers_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string qualifiers = 3;</code>
     */
    public Builder addQualifiers(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureQualifiersIsMutable();
      qualifiers_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string qualifiers = 3;</code>
     */
    public Builder addAllQualifiers(
        java.lang.Iterable<java.lang.String> values) {
      ensureQualifiersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, qualifiers_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string qualifiers = 3;</code>
     */
    public Builder clearQualifiers() {
      qualifiers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string qualifiers = 3;</code>
     */
    public Builder addQualifiersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureQualifiersIsMutable();
      qualifiers_.add(value);
      onChanged();
      return this;
    }

    private org.rti.amanzi.protobuf.Struct properties_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Struct, org.rti.amanzi.protobuf.Struct.Builder, org.rti.amanzi.protobuf.StructOrBuilder> propertiesBuilder_;
    /**
     * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
     */
    public boolean hasProperties() {
      return propertiesBuilder_ != null || properties_ != null;
    }
    /**
     * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
     */
    public org.rti.amanzi.protobuf.Struct getProperties() {
      if (propertiesBuilder_ == null) {
        return properties_ == null ? org.rti.amanzi.protobuf.Struct.getDefaultInstance() : properties_;
      } else {
        return propertiesBuilder_.getMessage();
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
     */
    public Builder setProperties(org.rti.amanzi.protobuf.Struct value) {
      if (propertiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        properties_ = value;
        onChanged();
      } else {
        propertiesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
     */
    public Builder setProperties(
        org.rti.amanzi.protobuf.Struct.Builder builderForValue) {
      if (propertiesBuilder_ == null) {
        properties_ = builderForValue.build();
        onChanged();
      } else {
        propertiesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
     */
    public Builder mergeProperties(org.rti.amanzi.protobuf.Struct value) {
      if (propertiesBuilder_ == null) {
        if (properties_ != null) {
          properties_ =
            org.rti.amanzi.protobuf.Struct.newBuilder(properties_).mergeFrom(value).buildPartial();
        } else {
          properties_ = value;
        }
        onChanged();
      } else {
        propertiesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
     */
    public Builder clearProperties() {
      if (propertiesBuilder_ == null) {
        properties_ = null;
        onChanged();
      } else {
        properties_ = null;
        propertiesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
     */
    public org.rti.amanzi.protobuf.Struct.Builder getPropertiesBuilder() {
      
      onChanged();
      return getPropertiesFieldBuilder().getBuilder();
    }
    /**
     * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
     */
    public org.rti.amanzi.protobuf.StructOrBuilder getPropertiesOrBuilder() {
      if (propertiesBuilder_ != null) {
        return propertiesBuilder_.getMessageOrBuilder();
      } else {
        return properties_ == null ?
            org.rti.amanzi.protobuf.Struct.getDefaultInstance() : properties_;
      }
    }
    /**
     * <code>.rti.amanzi.protobuf.Struct properties = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.Struct, org.rti.amanzi.protobuf.Struct.Builder, org.rti.amanzi.protobuf.StructOrBuilder> 
        getPropertiesFieldBuilder() {
      if (propertiesBuilder_ == null) {
        propertiesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.rti.amanzi.protobuf.Struct, org.rti.amanzi.protobuf.Struct.Builder, org.rti.amanzi.protobuf.StructOrBuilder>(
                getProperties(),
                getParentForChildren(),
                isClean());
        properties_ = null;
      }
      return propertiesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rti.amanzi.protobuf.TimeRecord)
  }

  // @@protoc_insertion_point(class_scope:rti.amanzi.protobuf.TimeRecord)
  private static final org.rti.amanzi.protobuf.TimeRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.rti.amanzi.protobuf.TimeRecord();
  }

  public static org.rti.amanzi.protobuf.TimeRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TimeRecord>
      PARSER = new com.google.protobuf.AbstractParser<TimeRecord>() {
    @java.lang.Override
    public TimeRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TimeRecord(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TimeRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TimeRecord> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.rti.amanzi.protobuf.TimeRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

