// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

public interface TimeSeriesMetaInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti.amanzi.protobuf.TimeSeriesMetaInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string code = 3;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 3;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string type = 4;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 4;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>.rti.amanzi.protobuf.Struct properties = 5;</code>
   */
  boolean hasProperties();
  /**
   * <code>.rti.amanzi.protobuf.Struct properties = 5;</code>
   */
  org.rti.amanzi.protobuf.Struct getProperties();
  /**
   * <code>.rti.amanzi.protobuf.Struct properties = 5;</code>
   */
  org.rti.amanzi.protobuf.StructOrBuilder getPropertiesOrBuilder();

  /**
   * <code>repeated .rti.amanzi.protobuf.Group groups = 6;</code>
   */
  java.util.List<org.rti.amanzi.protobuf.Group> 
      getGroupsList();
  /**
   * <code>repeated .rti.amanzi.protobuf.Group groups = 6;</code>
   */
  org.rti.amanzi.protobuf.Group getGroups(int index);
  /**
   * <code>repeated .rti.amanzi.protobuf.Group groups = 6;</code>
   */
  int getGroupsCount();
  /**
   * <code>repeated .rti.amanzi.protobuf.Group groups = 6;</code>
   */
  java.util.List<? extends org.rti.amanzi.protobuf.GroupOrBuilder> 
      getGroupsOrBuilderList();
  /**
   * <code>repeated .rti.amanzi.protobuf.Group groups = 6;</code>
   */
  org.rti.amanzi.protobuf.GroupOrBuilder getGroupsOrBuilder(
      int index);

  /**
   * <code>.rti.amanzi.protobuf.Source source = 7;</code>
   */
  boolean hasSource();
  /**
   * <code>.rti.amanzi.protobuf.Source source = 7;</code>
   */
  org.rti.amanzi.protobuf.Source getSource();
  /**
   * <code>.rti.amanzi.protobuf.Source source = 7;</code>
   */
  org.rti.amanzi.protobuf.SourceOrBuilder getSourceOrBuilder();

  /**
   * <code>.rti.amanzi.protobuf.SourceLocation sourceLocation = 8;</code>
   */
  boolean hasSourceLocation();
  /**
   * <code>.rti.amanzi.protobuf.SourceLocation sourceLocation = 8;</code>
   */
  org.rti.amanzi.protobuf.SourceLocation getSourceLocation();
  /**
   * <code>.rti.amanzi.protobuf.SourceLocation sourceLocation = 8;</code>
   */
  org.rti.amanzi.protobuf.SourceLocationOrBuilder getSourceLocationOrBuilder();

  /**
   * <code>.rti.amanzi.protobuf.Parameter parameter = 9;</code>
   */
  boolean hasParameter();
  /**
   * <code>.rti.amanzi.protobuf.Parameter parameter = 9;</code>
   */
  org.rti.amanzi.protobuf.Parameter getParameter();
  /**
   * <code>.rti.amanzi.protobuf.Parameter parameter = 9;</code>
   */
  org.rti.amanzi.protobuf.ParameterOrBuilder getParameterOrBuilder();

  /**
   * <code>.rti.amanzi.protobuf.TimeInfo timeInfo = 10;</code>
   */
  boolean hasTimeInfo();
  /**
   * <code>.rti.amanzi.protobuf.TimeInfo timeInfo = 10;</code>
   */
  org.rti.amanzi.protobuf.TimeInfo getTimeInfo();
  /**
   * <code>.rti.amanzi.protobuf.TimeInfo timeInfo = 10;</code>
   */
  org.rti.amanzi.protobuf.TimeInfoOrBuilder getTimeInfoOrBuilder();

  /**
   * <code>.rti.amanzi.protobuf.Origin origin = 11;</code>
   */
  boolean hasOrigin();
  /**
   * <code>.rti.amanzi.protobuf.Origin origin = 11;</code>
   */
  org.rti.amanzi.protobuf.Origin getOrigin();
  /**
   * <code>.rti.amanzi.protobuf.Origin origin = 11;</code>
   */
  org.rti.amanzi.protobuf.OriginOrBuilder getOriginOrBuilder();
}
