// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

/**
 * Protobuf type {@code rti.amanzi.protobuf.TimeSeries}
 */
public  final class TimeSeries extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rti.amanzi.protobuf.TimeSeries)
    TimeSeriesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TimeSeries.newBuilder() to construct.
  private TimeSeries(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TimeSeries() {
    data_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TimeSeries(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 26: {
            org.rti.amanzi.protobuf.TimeSeriesMetaInfo.Builder subBuilder = null;
            if (metaInfo_ != null) {
              subBuilder = metaInfo_.toBuilder();
            }
            metaInfo_ = input.readMessage(org.rti.amanzi.protobuf.TimeSeriesMetaInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metaInfo_);
              metaInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              data_ = new java.util.ArrayList<org.rti.amanzi.protobuf.TimeRecord>();
              mutable_bitField0_ |= 0x00000002;
            }
            data_.add(
                input.readMessage(org.rti.amanzi.protobuf.TimeRecord.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        data_ = java.util.Collections.unmodifiableList(data_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeSeries_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeSeries_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.rti.amanzi.protobuf.TimeSeries.class, org.rti.amanzi.protobuf.TimeSeries.Builder.class);
  }

  private int bitField0_;
  public static final int METAINFO_FIELD_NUMBER = 3;
  private org.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo_;
  /**
   * <pre>
   * a meta object describing the timeseries
   * </pre>
   *
   * <code>.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo = 3;</code>
   */
  public boolean hasMetaInfo() {
    return metaInfo_ != null;
  }
  /**
   * <pre>
   * a meta object describing the timeseries
   * </pre>
   *
   * <code>.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo = 3;</code>
   */
  public org.rti.amanzi.protobuf.TimeSeriesMetaInfo getMetaInfo() {
    return metaInfo_ == null ? org.rti.amanzi.protobuf.TimeSeriesMetaInfo.getDefaultInstance() : metaInfo_;
  }
  /**
   * <pre>
   * a meta object describing the timeseries
   * </pre>
   *
   * <code>.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo = 3;</code>
   */
  public org.rti.amanzi.protobuf.TimeSeriesMetaInfoOrBuilder getMetaInfoOrBuilder() {
    return getMetaInfo();
  }

  public static final int DATA_FIELD_NUMBER = 4;
  private java.util.List<org.rti.amanzi.protobuf.TimeRecord> data_;
  /**
   * <pre>
   * the time , value records of the timeseries
   * </pre>
   *
   * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
   */
  public java.util.List<org.rti.amanzi.protobuf.TimeRecord> getDataList() {
    return data_;
  }
  /**
   * <pre>
   * the time , value records of the timeseries
   * </pre>
   *
   * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
   */
  public java.util.List<? extends org.rti.amanzi.protobuf.TimeRecordOrBuilder> 
      getDataOrBuilderList() {
    return data_;
  }
  /**
   * <pre>
   * the time , value records of the timeseries
   * </pre>
   *
   * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
   */
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <pre>
   * the time , value records of the timeseries
   * </pre>
   *
   * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
   */
  public org.rti.amanzi.protobuf.TimeRecord getData(int index) {
    return data_.get(index);
  }
  /**
   * <pre>
   * the time , value records of the timeseries
   * </pre>
   *
   * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
   */
  public org.rti.amanzi.protobuf.TimeRecordOrBuilder getDataOrBuilder(
      int index) {
    return data_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (metaInfo_ != null) {
      output.writeMessage(3, getMetaInfo());
    }
    for (int i = 0; i < data_.size(); i++) {
      output.writeMessage(4, data_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (metaInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMetaInfo());
    }
    for (int i = 0; i < data_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, data_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.rti.amanzi.protobuf.TimeSeries)) {
      return super.equals(obj);
    }
    org.rti.amanzi.protobuf.TimeSeries other = (org.rti.amanzi.protobuf.TimeSeries) obj;

    if (hasMetaInfo() != other.hasMetaInfo()) return false;
    if (hasMetaInfo()) {
      if (!getMetaInfo()
          .equals(other.getMetaInfo())) return false;
    }
    if (!getDataList()
        .equals(other.getDataList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMetaInfo()) {
      hash = (37 * hash) + METAINFO_FIELD_NUMBER;
      hash = (53 * hash) + getMetaInfo().hashCode();
    }
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.rti.amanzi.protobuf.TimeSeries parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.TimeSeries parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeSeries parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.TimeSeries parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeSeries parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rti.amanzi.protobuf.TimeSeries parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeSeries parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.TimeSeries parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeSeries parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.TimeSeries parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rti.amanzi.protobuf.TimeSeries parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rti.amanzi.protobuf.TimeSeries parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.rti.amanzi.protobuf.TimeSeries prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rti.amanzi.protobuf.TimeSeries}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rti.amanzi.protobuf.TimeSeries)
      org.rti.amanzi.protobuf.TimeSeriesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeSeries_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeSeries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rti.amanzi.protobuf.TimeSeries.class, org.rti.amanzi.protobuf.TimeSeries.Builder.class);
    }

    // Construct using org.rti.amanzi.protobuf.TimeSeries.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (metaInfoBuilder_ == null) {
        metaInfo_ = null;
      } else {
        metaInfo_ = null;
        metaInfoBuilder_ = null;
      }
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        dataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.rti.amanzi.protobuf.Amanzi.internal_static_rti_amanzi_protobuf_TimeSeries_descriptor;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.TimeSeries getDefaultInstanceForType() {
      return org.rti.amanzi.protobuf.TimeSeries.getDefaultInstance();
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.TimeSeries build() {
      org.rti.amanzi.protobuf.TimeSeries result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.rti.amanzi.protobuf.TimeSeries buildPartial() {
      org.rti.amanzi.protobuf.TimeSeries result = new org.rti.amanzi.protobuf.TimeSeries(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (metaInfoBuilder_ == null) {
        result.metaInfo_ = metaInfo_;
      } else {
        result.metaInfo_ = metaInfoBuilder_.build();
      }
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.rti.amanzi.protobuf.TimeSeries) {
        return mergeFrom((org.rti.amanzi.protobuf.TimeSeries)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.rti.amanzi.protobuf.TimeSeries other) {
      if (other == org.rti.amanzi.protobuf.TimeSeries.getDefaultInstance()) return this;
      if (other.hasMetaInfo()) {
        mergeMetaInfo(other.getMetaInfo());
      }
      if (dataBuilder_ == null) {
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
      } else {
        if (!other.data_.isEmpty()) {
          if (dataBuilder_.isEmpty()) {
            dataBuilder_.dispose();
            dataBuilder_ = null;
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000002);
            dataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDataFieldBuilder() : null;
          } else {
            dataBuilder_.addAllMessages(other.data_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.rti.amanzi.protobuf.TimeSeries parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.rti.amanzi.protobuf.TimeSeries) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.TimeSeriesMetaInfo, org.rti.amanzi.protobuf.TimeSeriesMetaInfo.Builder, org.rti.amanzi.protobuf.TimeSeriesMetaInfoOrBuilder> metaInfoBuilder_;
    /**
     * <pre>
     * a meta object describing the timeseries
     * </pre>
     *
     * <code>.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo = 3;</code>
     */
    public boolean hasMetaInfo() {
      return metaInfoBuilder_ != null || metaInfo_ != null;
    }
    /**
     * <pre>
     * a meta object describing the timeseries
     * </pre>
     *
     * <code>.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo = 3;</code>
     */
    public org.rti.amanzi.protobuf.TimeSeriesMetaInfo getMetaInfo() {
      if (metaInfoBuilder_ == null) {
        return metaInfo_ == null ? org.rti.amanzi.protobuf.TimeSeriesMetaInfo.getDefaultInstance() : metaInfo_;
      } else {
        return metaInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * a meta object describing the timeseries
     * </pre>
     *
     * <code>.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo = 3;</code>
     */
    public Builder setMetaInfo(org.rti.amanzi.protobuf.TimeSeriesMetaInfo value) {
      if (metaInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metaInfo_ = value;
        onChanged();
      } else {
        metaInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * a meta object describing the timeseries
     * </pre>
     *
     * <code>.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo = 3;</code>
     */
    public Builder setMetaInfo(
        org.rti.amanzi.protobuf.TimeSeriesMetaInfo.Builder builderForValue) {
      if (metaInfoBuilder_ == null) {
        metaInfo_ = builderForValue.build();
        onChanged();
      } else {
        metaInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * a meta object describing the timeseries
     * </pre>
     *
     * <code>.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo = 3;</code>
     */
    public Builder mergeMetaInfo(org.rti.amanzi.protobuf.TimeSeriesMetaInfo value) {
      if (metaInfoBuilder_ == null) {
        if (metaInfo_ != null) {
          metaInfo_ =
            org.rti.amanzi.protobuf.TimeSeriesMetaInfo.newBuilder(metaInfo_).mergeFrom(value).buildPartial();
        } else {
          metaInfo_ = value;
        }
        onChanged();
      } else {
        metaInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * a meta object describing the timeseries
     * </pre>
     *
     * <code>.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo = 3;</code>
     */
    public Builder clearMetaInfo() {
      if (metaInfoBuilder_ == null) {
        metaInfo_ = null;
        onChanged();
      } else {
        metaInfo_ = null;
        metaInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * a meta object describing the timeseries
     * </pre>
     *
     * <code>.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo = 3;</code>
     */
    public org.rti.amanzi.protobuf.TimeSeriesMetaInfo.Builder getMetaInfoBuilder() {
      
      onChanged();
      return getMetaInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * a meta object describing the timeseries
     * </pre>
     *
     * <code>.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo = 3;</code>
     */
    public org.rti.amanzi.protobuf.TimeSeriesMetaInfoOrBuilder getMetaInfoOrBuilder() {
      if (metaInfoBuilder_ != null) {
        return metaInfoBuilder_.getMessageOrBuilder();
      } else {
        return metaInfo_ == null ?
            org.rti.amanzi.protobuf.TimeSeriesMetaInfo.getDefaultInstance() : metaInfo_;
      }
    }
    /**
     * <pre>
     * a meta object describing the timeseries
     * </pre>
     *
     * <code>.rti.amanzi.protobuf.TimeSeriesMetaInfo metaInfo = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rti.amanzi.protobuf.TimeSeriesMetaInfo, org.rti.amanzi.protobuf.TimeSeriesMetaInfo.Builder, org.rti.amanzi.protobuf.TimeSeriesMetaInfoOrBuilder> 
        getMetaInfoFieldBuilder() {
      if (metaInfoBuilder_ == null) {
        metaInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.rti.amanzi.protobuf.TimeSeriesMetaInfo, org.rti.amanzi.protobuf.TimeSeriesMetaInfo.Builder, org.rti.amanzi.protobuf.TimeSeriesMetaInfoOrBuilder>(
                getMetaInfo(),
                getParentForChildren(),
                isClean());
        metaInfo_ = null;
      }
      return metaInfoBuilder_;
    }

    private java.util.List<org.rti.amanzi.protobuf.TimeRecord> data_ =
      java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        data_ = new java.util.ArrayList<org.rti.amanzi.protobuf.TimeRecord>(data_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.rti.amanzi.protobuf.TimeRecord, org.rti.amanzi.protobuf.TimeRecord.Builder, org.rti.amanzi.protobuf.TimeRecordOrBuilder> dataBuilder_;

    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public java.util.List<org.rti.amanzi.protobuf.TimeRecord> getDataList() {
      if (dataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(data_);
      } else {
        return dataBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public int getDataCount() {
      if (dataBuilder_ == null) {
        return data_.size();
      } else {
        return dataBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public org.rti.amanzi.protobuf.TimeRecord getData(int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);
      } else {
        return dataBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public Builder setData(
        int index, org.rti.amanzi.protobuf.TimeRecord value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
      } else {
        dataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public Builder setData(
        int index, org.rti.amanzi.protobuf.TimeRecord.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public Builder addData(org.rti.amanzi.protobuf.TimeRecord value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
      } else {
        dataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public Builder addData(
        int index, org.rti.amanzi.protobuf.TimeRecord value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(index, value);
        onChanged();
      } else {
        dataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public Builder addData(
        org.rti.amanzi.protobuf.TimeRecord.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public Builder addData(
        int index, org.rti.amanzi.protobuf.TimeRecord.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends org.rti.amanzi.protobuf.TimeRecord> values) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
      } else {
        dataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public Builder removeData(int index) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.remove(index);
        onChanged();
      } else {
        dataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public org.rti.amanzi.protobuf.TimeRecord.Builder getDataBuilder(
        int index) {
      return getDataFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public org.rti.amanzi.protobuf.TimeRecordOrBuilder getDataOrBuilder(
        int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);  } else {
        return dataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public java.util.List<? extends org.rti.amanzi.protobuf.TimeRecordOrBuilder> 
         getDataOrBuilderList() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(data_);
      }
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public org.rti.amanzi.protobuf.TimeRecord.Builder addDataBuilder() {
      return getDataFieldBuilder().addBuilder(
          org.rti.amanzi.protobuf.TimeRecord.getDefaultInstance());
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public org.rti.amanzi.protobuf.TimeRecord.Builder addDataBuilder(
        int index) {
      return getDataFieldBuilder().addBuilder(
          index, org.rti.amanzi.protobuf.TimeRecord.getDefaultInstance());
    }
    /**
     * <pre>
     * the time , value records of the timeseries
     * </pre>
     *
     * <code>repeated .rti.amanzi.protobuf.TimeRecord data = 4;</code>
     */
    public java.util.List<org.rti.amanzi.protobuf.TimeRecord.Builder> 
         getDataBuilderList() {
      return getDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.rti.amanzi.protobuf.TimeRecord, org.rti.amanzi.protobuf.TimeRecord.Builder, org.rti.amanzi.protobuf.TimeRecordOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.rti.amanzi.protobuf.TimeRecord, org.rti.amanzi.protobuf.TimeRecord.Builder, org.rti.amanzi.protobuf.TimeRecordOrBuilder>(
                data_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rti.amanzi.protobuf.TimeSeries)
  }

  // @@protoc_insertion_point(class_scope:rti.amanzi.protobuf.TimeSeries)
  private static final org.rti.amanzi.protobuf.TimeSeries DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.rti.amanzi.protobuf.TimeSeries();
  }

  public static org.rti.amanzi.protobuf.TimeSeries getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TimeSeries>
      PARSER = new com.google.protobuf.AbstractParser<TimeSeries>() {
    @java.lang.Override
    public TimeSeries parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TimeSeries(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TimeSeries> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TimeSeries> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.rti.amanzi.protobuf.TimeSeries getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

