// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amanzi.proto

package org.rti.amanzi.protobuf;

public interface ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti.amanzi.protobuf.Value)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Represents a null value.
   * </pre>
   *
   * <code>.rti.amanzi.protobuf.NullValue null_value = 1;</code>
   */
  int getNullValueValue();
  /**
   * <pre>
   * Represents a null value.
   * </pre>
   *
   * <code>.rti.amanzi.protobuf.NullValue null_value = 1;</code>
   */
  org.rti.amanzi.protobuf.NullValue getNullValue();

  /**
   * <pre>
   * Represents a double value.
   * </pre>
   *
   * <code>double number_value = 2;</code>
   */
  double getNumberValue();

  /**
   * <pre>
   * Represents a string value.
   * </pre>
   *
   * <code>string string_value = 3;</code>
   */
  java.lang.String getStringValue();
  /**
   * <pre>
   * Represents a string value.
   * </pre>
   *
   * <code>string string_value = 3;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <pre>
   * Represents a boolean value.
   * </pre>
   *
   * <code>bool bool_value = 4;</code>
   */
  boolean getBoolValue();

  /**
   * <pre>
   * Represents a structured value.
   * </pre>
   *
   * <code>.rti.amanzi.protobuf.Struct struct_value = 5;</code>
   */
  boolean hasStructValue();
  /**
   * <pre>
   * Represents a structured value.
   * </pre>
   *
   * <code>.rti.amanzi.protobuf.Struct struct_value = 5;</code>
   */
  org.rti.amanzi.protobuf.Struct getStructValue();
  /**
   * <pre>
   * Represents a structured value.
   * </pre>
   *
   * <code>.rti.amanzi.protobuf.Struct struct_value = 5;</code>
   */
  org.rti.amanzi.protobuf.StructOrBuilder getStructValueOrBuilder();

  /**
   * <pre>
   * Represents a repeated `Value`.
   * </pre>
   *
   * <code>.rti.amanzi.protobuf.ListValue list_value = 6;</code>
   */
  boolean hasListValue();
  /**
   * <pre>
   * Represents a repeated `Value`.
   * </pre>
   *
   * <code>.rti.amanzi.protobuf.ListValue list_value = 6;</code>
   */
  org.rti.amanzi.protobuf.ListValue getListValue();
  /**
   * <pre>
   * Represents a repeated `Value`.
   * </pre>
   *
   * <code>.rti.amanzi.protobuf.ListValue list_value = 6;</code>
   */
  org.rti.amanzi.protobuf.ListValueOrBuilder getListValueOrBuilder();

  public org.rti.amanzi.protobuf.Value.KindCase getKindCase();
}
