// Code generated by protoc-gen-go. DO NOT EDIT.
// source: amanzi.proto

package rti_amanzi_protobuf

import (
	fmt "fmt"
	_struct "github.com/golang/proto/ptypes/struct"
	timestamp "github.com/golang/proto/ptypes/timestamp"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataType int32

const (
	DataType_double_value DataType = 0
	DataType_float_value  DataType = 1
	DataType_int64_value  DataType = 2
	DataType_int32_value  DataType = 3
	DataType_uint64_value DataType = 4
	DataType_uint32_value DataType = 5
	DataType_string_value DataType = 7
)

var DataType_name = map[int32]string{
	0: "double_value",
	1: "float_value",
	2: "int64_value",
	3: "int32_value",
	4: "uint64_value",
	5: "uint32_value",
	7: "string_value",
}

var DataType_value = map[string]int32{
	"double_value": 0,
	"float_value":  1,
	"int64_value":  2,
	"int32_value":  3,
	"uint64_value": 4,
	"uint32_value": 5,
	"string_value": 7,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e63c41d33ddcceee, []int{0}
}

// `NullValue` is a singleton enumeration to represent the null value for the
// `Value` type union.
//
//  The JSON representation for `NullValue` is JSON `null`.
type NullValue int32

const (
	// Null value.
	NullValue_NULL_VALUE NullValue = 0
)

var NullValue_name = map[int32]string{
	0: "NULL_VALUE",
}

var NullValue_value = map[string]int32{
	"NULL_VALUE": 0,
}

func (x NullValue) String() string {
	return proto.EnumName(NullValue_name, int32(x))
}

func (NullValue) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e63c41d33ddcceee, []int{1}
}

type Value struct {
	// Types that are valid to be assigned to Kind:
	//	*Value_DoubleValue
	//	*Value_FloatValue
	//	*Value_Int64Value
	//	*Value_Int32Value
	//	*Value_Uint64Value
	//	*Value_Uint32Value
	//	*Value_StringValue
	//	*Value_NullValue
	Kind                 isValue_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63c41d33ddcceee, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Kind interface {
	isValue_Kind()
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,1,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,2,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Value_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_Int32Value struct {
	Int32Value int32 `protobuf:"varint,4,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type Value_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,5,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type Value_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,6,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,7,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_NullValue struct {
	NullValue NullValue `protobuf:"varint,8,opt,name=null_value,json=nullValue,proto3,enum=rti.amanzi.protobuf.NullValue,oneof"`
}

func (*Value_DoubleValue) isValue_Kind() {}

func (*Value_FloatValue) isValue_Kind() {}

func (*Value_Int64Value) isValue_Kind() {}

func (*Value_Int32Value) isValue_Kind() {}

func (*Value_Uint64Value) isValue_Kind() {}

func (*Value_Uint32Value) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_NullValue) isValue_Kind() {}

func (m *Value) GetKind() isValue_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Value) GetDoubleValue() float64 {
	if x, ok := m.GetKind().(*Value_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Value) GetFloatValue() float32 {
	if x, ok := m.GetKind().(*Value_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *Value) GetInt64Value() int64 {
	if x, ok := m.GetKind().(*Value_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (m *Value) GetInt32Value() int32 {
	if x, ok := m.GetKind().(*Value_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *Value) GetUint64Value() uint64 {
	if x, ok := m.GetKind().(*Value_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (m *Value) GetUint32Value() uint32 {
	if x, ok := m.GetKind().(*Value_Uint32Value); ok {
		return x.Uint32Value
	}
	return 0
}

func (m *Value) GetStringValue() string {
	if x, ok := m.GetKind().(*Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Value) GetNullValue() NullValue {
	if x, ok := m.GetKind().(*Value_NullValue); ok {
		return x.NullValue
	}
	return NullValue_NULL_VALUE
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_DoubleValue)(nil),
		(*Value_FloatValue)(nil),
		(*Value_Int64Value)(nil),
		(*Value_Int32Value)(nil),
		(*Value_Uint64Value)(nil),
		(*Value_Uint32Value)(nil),
		(*Value_StringValue)(nil),
		(*Value_NullValue)(nil),
	}
}

// A Source object holds spatial and origin meta data associated with the timeseries
type Source struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63c41d33ddcceee, []int{1}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Source) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Elevation struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Units                string   `protobuf:"bytes,2,opt,name=units,proto3" json:"units,omitempty"`
	Datum                string   `protobuf:"bytes,3,opt,name=datum,proto3" json:"datum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Elevation) Reset()         { *m = Elevation{} }
func (m *Elevation) String() string { return proto.CompactTextString(m) }
func (*Elevation) ProtoMessage()    {}
func (*Elevation) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63c41d33ddcceee, []int{2}
}

func (m *Elevation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Elevation.Unmarshal(m, b)
}
func (m *Elevation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Elevation.Marshal(b, m, deterministic)
}
func (m *Elevation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Elevation.Merge(m, src)
}
func (m *Elevation) XXX_Size() int {
	return xxx_messageInfo_Elevation.Size(m)
}
func (m *Elevation) XXX_DiscardUnknown() {
	xxx_messageInfo_Elevation.DiscardUnknown(m)
}

var xxx_messageInfo_Elevation proto.InternalMessageInfo

func (m *Elevation) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Elevation) GetUnits() string {
	if m != nil {
		return m.Units
	}
	return ""
}

func (m *Elevation) GetDatum() string {
	if m != nil {
		return m.Datum
	}
	return ""
}

type SourceLocation struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string     `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Elevation            *Elevation `protobuf:"bytes,3,opt,name=elevation,proto3" json:"elevation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SourceLocation) Reset()         { *m = SourceLocation{} }
func (m *SourceLocation) String() string { return proto.CompactTextString(m) }
func (*SourceLocation) ProtoMessage()    {}
func (*SourceLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63c41d33ddcceee, []int{3}
}

func (m *SourceLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceLocation.Unmarshal(m, b)
}
func (m *SourceLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceLocation.Marshal(b, m, deterministic)
}
func (m *SourceLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceLocation.Merge(m, src)
}
func (m *SourceLocation) XXX_Size() int {
	return xxx_messageInfo_SourceLocation.Size(m)
}
func (m *SourceLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceLocation.DiscardUnknown(m)
}

var xxx_messageInfo_SourceLocation proto.InternalMessageInfo

func (m *SourceLocation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SourceLocation) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SourceLocation) GetElevation() *Elevation {
	if m != nil {
		return m.Elevation
	}
	return nil
}

type Parameter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Units                string   `protobuf:"bytes,3,opt,name=units,proto3" json:"units,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63c41d33ddcceee, []int{4}
}

func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Parameter) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Parameter) GetUnits() string {
	if m != nil {
		return m.Units
	}
	return ""
}

type TimeInfo struct {
	ReferenceTime        *timestamp.Timestamp `protobuf:"bytes,1,opt,name=referenceTime,proto3" json:"referenceTime,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	WindowedInterval     string               `protobuf:"bytes,4,opt,name=windowedInterval,proto3" json:"windowedInterval,omitempty"`
	Interval             string               `protobuf:"bytes,5,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimeInfo) Reset()         { *m = TimeInfo{} }
func (m *TimeInfo) String() string { return proto.CompactTextString(m) }
func (*TimeInfo) ProtoMessage()    {}
func (*TimeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63c41d33ddcceee, []int{5}
}

func (m *TimeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeInfo.Unmarshal(m, b)
}
func (m *TimeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeInfo.Marshal(b, m, deterministic)
}
func (m *TimeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeInfo.Merge(m, src)
}
func (m *TimeInfo) XXX_Size() int {
	return xxx_messageInfo_TimeInfo.Size(m)
}
func (m *TimeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TimeInfo proto.InternalMessageInfo

func (m *TimeInfo) GetReferenceTime() *timestamp.Timestamp {
	if m != nil {
		return m.ReferenceTime
	}
	return nil
}

func (m *TimeInfo) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *TimeInfo) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *TimeInfo) GetWindowedInterval() string {
	if m != nil {
		return m.WindowedInterval
	}
	return ""
}

func (m *TimeInfo) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

type Origin struct {
	ModifiedOn           *timestamp.Timestamp `protobuf:"bytes,1,opt,name=modifiedOn,proto3" json:"modifiedOn,omitempty"`
	Description          string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceIds         []string             `protobuf:"bytes,3,rep,name=referenceIds,proto3" json:"referenceIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Origin) Reset()         { *m = Origin{} }
func (m *Origin) String() string { return proto.CompactTextString(m) }
func (*Origin) ProtoMessage()    {}
func (*Origin) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63c41d33ddcceee, []int{6}
}

func (m *Origin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Origin.Unmarshal(m, b)
}
func (m *Origin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Origin.Marshal(b, m, deterministic)
}
func (m *Origin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Origin.Merge(m, src)
}
func (m *Origin) XXX_Size() int {
	return xxx_messageInfo_Origin.Size(m)
}
func (m *Origin) XXX_DiscardUnknown() {
	xxx_messageInfo_Origin.DiscardUnknown(m)
}

var xxx_messageInfo_Origin proto.InternalMessageInfo

func (m *Origin) GetModifiedOn() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedOn
	}
	return nil
}

func (m *Origin) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Origin) GetReferenceIds() []string {
	if m != nil {
		return m.ReferenceIds
	}
	return nil
}

type Group struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63c41d33ddcceee, []int{7}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type TimeSeriesMetaInfo struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string          `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Type                 string          `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	DataType             DataType        `protobuf:"varint,5,opt,name=dataType,proto3,enum=rti.amanzi.protobuf.DataType" json:"dataType,omitempty"`
	Statistic            string          `protobuf:"bytes,6,opt,name=statistic,proto3" json:"statistic,omitempty"`
	Properties           *_struct.Struct `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	Groups               []*Group        `protobuf:"bytes,8,rep,name=groups,proto3" json:"groups,omitempty"`
	Source               *Source         `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	SourceLocation       *SourceLocation `protobuf:"bytes,10,opt,name=sourceLocation,proto3" json:"sourceLocation,omitempty"`
	Parameter            *Parameter      `protobuf:"bytes,11,opt,name=parameter,proto3" json:"parameter,omitempty"`
	TimeInfo             *TimeInfo       `protobuf:"bytes,12,opt,name=timeInfo,proto3" json:"timeInfo,omitempty"`
	Origin               *Origin         `protobuf:"bytes,13,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TimeSeriesMetaInfo) Reset()         { *m = TimeSeriesMetaInfo{} }
func (m *TimeSeriesMetaInfo) String() string { return proto.CompactTextString(m) }
func (*TimeSeriesMetaInfo) ProtoMessage()    {}
func (*TimeSeriesMetaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63c41d33ddcceee, []int{8}
}

func (m *TimeSeriesMetaInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeSeriesMetaInfo.Unmarshal(m, b)
}
func (m *TimeSeriesMetaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeSeriesMetaInfo.Marshal(b, m, deterministic)
}
func (m *TimeSeriesMetaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeSeriesMetaInfo.Merge(m, src)
}
func (m *TimeSeriesMetaInfo) XXX_Size() int {
	return xxx_messageInfo_TimeSeriesMetaInfo.Size(m)
}
func (m *TimeSeriesMetaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeSeriesMetaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TimeSeriesMetaInfo proto.InternalMessageInfo

func (m *TimeSeriesMetaInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TimeSeriesMetaInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TimeSeriesMetaInfo) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TimeSeriesMetaInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TimeSeriesMetaInfo) GetDataType() DataType {
	if m != nil {
		return m.DataType
	}
	return DataType_double_value
}

func (m *TimeSeriesMetaInfo) GetStatistic() string {
	if m != nil {
		return m.Statistic
	}
	return ""
}

func (m *TimeSeriesMetaInfo) GetProperties() *_struct.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *TimeSeriesMetaInfo) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *TimeSeriesMetaInfo) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *TimeSeriesMetaInfo) GetSourceLocation() *SourceLocation {
	if m != nil {
		return m.SourceLocation
	}
	return nil
}

func (m *TimeSeriesMetaInfo) GetParameter() *Parameter {
	if m != nil {
		return m.Parameter
	}
	return nil
}

func (m *TimeSeriesMetaInfo) GetTimeInfo() *TimeInfo {
	if m != nil {
		return m.TimeInfo
	}
	return nil
}

func (m *TimeSeriesMetaInfo) GetOrigin() *Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

type TimeRecord struct {
	Datetime             *timestamp.Timestamp `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Value                *Value               `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Qualifiers           []string             `protobuf:"bytes,3,rep,name=qualifiers,proto3" json:"qualifiers,omitempty"`
	Properties           *_struct.Struct      `protobuf:"bytes,4,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimeRecord) Reset()         { *m = TimeRecord{} }
func (m *TimeRecord) String() string { return proto.CompactTextString(m) }
func (*TimeRecord) ProtoMessage()    {}
func (*TimeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63c41d33ddcceee, []int{9}
}

func (m *TimeRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRecord.Unmarshal(m, b)
}
func (m *TimeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRecord.Marshal(b, m, deterministic)
}
func (m *TimeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRecord.Merge(m, src)
}
func (m *TimeRecord) XXX_Size() int {
	return xxx_messageInfo_TimeRecord.Size(m)
}
func (m *TimeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRecord proto.InternalMessageInfo

func (m *TimeRecord) GetDatetime() *timestamp.Timestamp {
	if m != nil {
		return m.Datetime
	}
	return nil
}

func (m *TimeRecord) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TimeRecord) GetQualifiers() []string {
	if m != nil {
		return m.Qualifiers
	}
	return nil
}

func (m *TimeRecord) GetProperties() *_struct.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

type TimeSeries struct {
	// a meta object describing the timeseries
	MetaInfo *TimeSeriesMetaInfo `protobuf:"bytes,1,opt,name=metaInfo,proto3" json:"metaInfo,omitempty"`
	// the time , value records of the timeseries
	Data                 []*TimeRecord `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TimeSeries) Reset()         { *m = TimeSeries{} }
func (m *TimeSeries) String() string { return proto.CompactTextString(m) }
func (*TimeSeries) ProtoMessage()    {}
func (*TimeSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63c41d33ddcceee, []int{10}
}

func (m *TimeSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeSeries.Unmarshal(m, b)
}
func (m *TimeSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeSeries.Marshal(b, m, deterministic)
}
func (m *TimeSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeSeries.Merge(m, src)
}
func (m *TimeSeries) XXX_Size() int {
	return xxx_messageInfo_TimeSeries.Size(m)
}
func (m *TimeSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeSeries.DiscardUnknown(m)
}

var xxx_messageInfo_TimeSeries proto.InternalMessageInfo

func (m *TimeSeries) GetMetaInfo() *TimeSeriesMetaInfo {
	if m != nil {
		return m.MetaInfo
	}
	return nil
}

func (m *TimeSeries) GetData() []*TimeRecord {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("rti.amanzi.protobuf.DataType", DataType_name, DataType_value)
	proto.RegisterEnum("rti.amanzi.protobuf.NullValue", NullValue_name, NullValue_value)
	proto.RegisterType((*Value)(nil), "rti.amanzi.protobuf.Value")
	proto.RegisterType((*Source)(nil), "rti.amanzi.protobuf.Source")
	proto.RegisterType((*Elevation)(nil), "rti.amanzi.protobuf.Elevation")
	proto.RegisterType((*SourceLocation)(nil), "rti.amanzi.protobuf.SourceLocation")
	proto.RegisterType((*Parameter)(nil), "rti.amanzi.protobuf.Parameter")
	proto.RegisterType((*TimeInfo)(nil), "rti.amanzi.protobuf.TimeInfo")
	proto.RegisterType((*Origin)(nil), "rti.amanzi.protobuf.Origin")
	proto.RegisterType((*Group)(nil), "rti.amanzi.protobuf.Group")
	proto.RegisterType((*TimeSeriesMetaInfo)(nil), "rti.amanzi.protobuf.TimeSeriesMetaInfo")
	proto.RegisterType((*TimeRecord)(nil), "rti.amanzi.protobuf.TimeRecord")
	proto.RegisterType((*TimeSeries)(nil), "rti.amanzi.protobuf.TimeSeries")
}

func init() { proto.RegisterFile("amanzi.proto", fileDescriptor_e63c41d33ddcceee) }

var fileDescriptor_e63c41d33ddcceee = []byte{
	// 918 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x96, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0xc7, 0xe3, 0xc4, 0xce, 0xc6, 0x27, 0xbb, 0xc1, 0x1a, 0x2a, 0x61, 0x6d, 0x4b, 0x6b, 0xdc,
	0x0b, 0xac, 0x15, 0x4a, 0xab, 0x04, 0x15, 0x81, 0x90, 0x80, 0x96, 0x8a, 0x8d, 0xd8, 0x7e, 0x68,
	0x76, 0xdb, 0xdb, 0x6a, 0x36, 0x9e, 0x44, 0x23, 0x6c, 0x4f, 0x18, 0x8f, 0xb7, 0x82, 0x7b, 0xb8,
	0xe0, 0xdd, 0x10, 0x77, 0x3c, 0x09, 0x0f, 0x80, 0xe6, 0xc3, 0x8e, 0xb3, 0x9b, 0x4d, 0x73, 0x37,
	0xf3, 0xcf, 0xef, 0x1c, 0x9f, 0x39, 0x1f, 0x33, 0x81, 0x43, 0x92, 0x93, 0xe2, 0x77, 0x36, 0x5e,
	0x09, 0x2e, 0x39, 0xfa, 0x58, 0x48, 0x36, 0x6e, 0x2b, 0x97, 0xd5, 0xe2, 0xf8, 0xde, 0x92, 0xf3,
	0x65, 0x46, 0x1f, 0xd5, 0xc2, 0xa3, 0x52, 0x8a, 0x6a, 0x2e, 0x0d, 0x70, 0xfc, 0xe0, 0xfa, 0xaf,
	0x92, 0xe5, 0xb4, 0x94, 0x24, 0x5f, 0x19, 0x20, 0xfe, 0xbb, 0x0b, 0xde, 0x5b, 0x92, 0x55, 0x14,
	0x3d, 0x84, 0xc3, 0x94, 0x57, 0x97, 0x19, 0x7d, 0x77, 0xa5, 0xf6, 0xa1, 0x13, 0x39, 0x89, 0x73,
	0xda, 0xc1, 0x43, 0xa3, 0x1a, 0xe8, 0x33, 0x18, 0x2e, 0x32, 0x4e, 0xa4, 0x65, 0xba, 0x91, 0x93,
	0x74, 0x4f, 0x3b, 0x18, 0xb4, 0xd8, 0x20, 0xac, 0x90, 0x4f, 0xbe, 0xb4, 0x48, 0x2f, 0x72, 0x92,
	0x9e, 0x42, 0xb4, 0xd8, 0x46, 0xa6, 0x13, 0x8b, 0xb8, 0x91, 0x93, 0x78, 0x16, 0x99, 0x4e, 0x9a,
	0x68, 0xaa, 0xb6, 0x1b, 0x2f, 0x72, 0x12, 0x57, 0x45, 0x53, 0xb5, 0xfc, 0x58, 0xa8, 0x71, 0xd4,
	0x8f, 0x9c, 0xe4, 0xa8, 0x86, 0x5a, 0x9e, 0x4a, 0x29, 0x58, 0xb1, 0xb4, 0xd0, 0x41, 0xe4, 0x24,
	0xbe, 0x82, 0x8c, 0x6a, 0xa0, 0xef, 0x00, 0x8a, 0x2a, 0xcb, 0x2c, 0x32, 0x88, 0x9c, 0x64, 0x34,
	0xb9, 0x3f, 0xde, 0x92, 0xef, 0xf1, 0xcb, 0x2a, 0xcb, 0xb4, 0xcd, 0x69, 0x07, 0xfb, 0x45, 0xbd,
	0x79, 0xda, 0x07, 0xf7, 0x17, 0x56, 0xa4, 0xf1, 0x63, 0xe8, 0x9f, 0xf3, 0x4a, 0xcc, 0x29, 0x42,
	0xe0, 0x16, 0x24, 0x37, 0x79, 0xf4, 0xb1, 0x5e, 0x2b, 0x6d, 0xce, 0x53, 0x93, 0x37, 0x1f, 0xeb,
	0x75, 0xfc, 0x02, 0xfc, 0xe7, 0x19, 0xbd, 0x22, 0x92, 0xf1, 0x02, 0xdd, 0x01, 0xaf, 0x95, 0x7d,
	0x6c, 0x36, 0x4a, 0xad, 0x0a, 0x26, 0x4b, 0x6b, 0x67, 0x36, 0x4a, 0x4d, 0x89, 0xac, 0x72, 0x9d,
	0x62, 0x1f, 0x9b, 0x4d, 0x7c, 0x05, 0x23, 0x13, 0xc0, 0x19, 0x9f, 0x1b, 0x9f, 0x7b, 0x06, 0x82,
	0xbe, 0x05, 0x9f, 0xd6, 0x81, 0x68, 0x9f, 0xc3, 0x5b, 0x52, 0xd0, 0x84, 0x8b, 0xd7, 0x06, 0xf1,
	0x0c, 0xfc, 0xd7, 0x44, 0x90, 0x9c, 0x4a, 0x2a, 0xf6, 0xfe, 0x64, 0x73, 0xb0, 0x5e, 0xeb, 0x60,
	0xf1, 0x7f, 0x0e, 0x0c, 0x2e, 0x58, 0x4e, 0x67, 0xc5, 0x82, 0xa3, 0xef, 0xe1, 0x48, 0xd0, 0x05,
	0x15, 0xb4, 0x98, 0x53, 0x25, 0x6a, 0x9f, 0xc3, 0xc9, 0xf1, 0xd8, 0x74, 0xf6, 0x3a, 0xaa, 0x8b,
	0xba, 0xb3, 0xf1, 0xa6, 0x01, 0x7a, 0x0c, 0x5e, 0x29, 0x89, 0x90, 0xfa, 0xcb, 0xbb, 0x2d, 0x0d,
	0x88, 0xbe, 0x80, 0x1e, 0x2d, 0x52, 0x9b, 0x83, 0x5d, 0xbc, 0xc2, 0xd0, 0x09, 0x04, 0xef, 0x59,
	0x91, 0xf2, 0xf7, 0x34, 0x9d, 0x15, 0x92, 0x8a, 0x2b, 0x92, 0xe9, 0x96, 0xf6, 0xf1, 0x0d, 0x1d,
	0x1d, 0xc3, 0x80, 0xd5, 0x8c, 0xa7, 0x99, 0x66, 0x1f, 0xff, 0xe5, 0x40, 0xff, 0x95, 0x60, 0x4b,
	0x56, 0xa0, 0x6f, 0x00, 0x72, 0x9e, 0xb2, 0x05, 0xa3, 0xe9, 0xab, 0x62, 0x8f, 0x13, 0xb7, 0x68,
	0x14, 0xc1, 0x30, 0xa5, 0xe5, 0x5c, 0xb0, 0x95, 0x2e, 0xa4, 0x49, 0x77, 0x5b, 0x42, 0x31, 0x1c,
	0x36, 0x19, 0x9a, 0xa5, 0x2a, 0xf9, 0xbd, 0xc4, 0xc7, 0x1b, 0x5a, 0xfc, 0x0c, 0xbc, 0x9f, 0x04,
	0xaf, 0x56, 0x28, 0x84, 0x83, 0xa5, 0x5a, 0xcc, 0x52, 0x5b, 0xcd, 0x7a, 0xfb, 0xe1, 0x0f, 0xc5,
	0xff, 0xba, 0x80, 0x54, 0x90, 0xe7, 0x54, 0x30, 0x5a, 0xbe, 0xa0, 0x92, 0xe8, 0x92, 0x8e, 0xa0,
	0xcb, 0x6a, 0x6f, 0x5d, 0x96, 0x36, 0xdd, 0xd2, 0xdd, 0xd2, 0x2d, 0xbd, 0x56, 0xb7, 0x20, 0x70,
	0xe5, 0x6f, 0x2b, 0x6a, 0x93, 0xab, 0xd7, 0xe8, 0x6b, 0x18, 0xa4, 0x44, 0x92, 0x0b, 0xa5, 0x7b,
	0x7a, 0x6c, 0x3f, 0xdd, 0xda, 0xb3, 0x3f, 0x5a, 0x08, 0x37, 0x38, 0xba, 0x07, 0x7e, 0x29, 0x89,
	0x64, 0xa5, 0x64, 0x73, 0x7d, 0x75, 0xf8, 0x78, 0x2d, 0xa0, 0xaf, 0x00, 0x56, 0x82, 0xaf, 0xa8,
	0x90, 0x8c, 0x96, 0xfa, 0xd2, 0x18, 0x4e, 0x3e, 0xb9, 0x51, 0x82, 0x73, 0x7d, 0xd9, 0xe2, 0x16,
	0x8a, 0x26, 0xd0, 0xd7, 0x19, 0x2a, 0xc3, 0x41, 0xd4, 0xd3, 0x75, 0xdb, 0x16, 0x8f, 0x4e, 0x2e,
	0xb6, 0x24, 0x9a, 0x42, 0xbf, 0xd4, 0x43, 0x1b, 0xfa, 0xfa, 0x43, 0x77, 0xb7, 0xda, 0x98, 0xb9,
	0xc6, 0x16, 0x45, 0x3f, 0xc3, 0xa8, 0xdc, 0x98, 0xf4, 0x10, 0xb4, 0xf1, 0xc3, 0x1d, 0xc6, 0x35,
	0x8a, 0xaf, 0x99, 0xaa, 0xe1, 0x5f, 0xd5, 0xe3, 0x1b, 0x0e, 0x77, 0x0c, 0x7f, 0x33, 0xe4, 0x78,
	0x6d, 0xa0, 0xaa, 0x20, 0xed, 0xc0, 0x86, 0x87, 0xda, 0x78, 0x7b, 0x15, 0xea, 0xa9, 0xc6, 0x0d,
	0xae, 0x8e, 0xce, 0x75, 0xd3, 0x87, 0x47, 0x3b, 0x8e, 0x6e, 0xe6, 0x02, 0x5b, 0x34, 0xfe, 0xc7,
	0x01, 0x50, 0xbe, 0x30, 0x9d, 0x73, 0x91, 0xa2, 0x27, 0xba, 0x09, 0xa8, 0xdc, 0xef, 0x7a, 0x68,
	0x58, 0x75, 0x33, 0xac, 0xdf, 0xb1, 0xdb, 0x2a, 0xa5, 0xef, 0xf7, 0xfa, 0x26, 0xbe, 0x0f, 0xf0,
	0x6b, 0x45, 0x32, 0x35, 0x6b, 0xa2, 0x1e, 0x9c, 0x96, 0x72, 0xad, 0x6b, 0xdc, 0xbd, 0xbb, 0x26,
	0xfe, 0xd3, 0x9e, 0xc8, 0x8c, 0x0a, 0x7a, 0x06, 0x83, 0xdc, 0x8e, 0x8b, 0x3d, 0xd1, 0xe7, 0xb7,
	0x26, 0x74, 0x73, 0xba, 0x70, 0x63, 0x88, 0xa6, 0xe0, 0xaa, 0x66, 0xd7, 0x61, 0x0e, 0x27, 0x0f,
	0x6e, 0x75, 0x60, 0xb2, 0x88, 0x35, 0x7c, 0xf2, 0x87, 0x03, 0x83, 0x7a, 0x58, 0x50, 0xb0, 0xf9,
	0x9f, 0x20, 0xe8, 0xa0, 0x8f, 0x36, 0xfe, 0x00, 0x04, 0x8e, 0x12, 0x5a, 0xef, 0x74, 0xd0, 0xb5,
	0x42, 0xfd, 0x26, 0x07, 0x3d, 0xe5, 0xa4, 0xfd, 0x94, 0x07, 0x6e, 0xad, 0x34, 0x8c, 0xa7, 0x94,
	0xf6, 0x23, 0x1d, 0x1c, 0x9c, 0xdc, 0x05, 0xbf, 0x79, 0x6a, 0xd1, 0x08, 0xe0, 0xe5, 0x9b, 0xb3,
	0xb3, 0x77, 0x6f, 0x7f, 0x38, 0x7b, 0xf3, 0x3c, 0xe8, 0x3c, 0x0d, 0xe1, 0x0e, 0x17, 0xcb, 0x1b,
	0x07, 0x7a, 0xed, 0x5c, 0xf6, 0xf5, 0x62, 0xfa, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71, 0xd4,
	0x66, 0xb8, 0x3a, 0x09, 0x00, 0x00,
}
