# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/rti/geometry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/rti/geometry.proto',
  package='rti.amanzi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bprotobuf/rti/geometry.proto\x12\nrti.amanzi\"\xb6\x01\n\x07\x46\x65\x61ture\x12&\n\x08geometry\x18\x01 \x01(\x0b\x32\x14.rti.amanzi.Geometry\x12\x0c\n\x02id\x18\x0b \x01(\tH\x00\x12\x10\n\x06int_id\x18\x0c \x01(\x12H\x00\x12!\n\x06values\x18\r \x03(\x0b\x32\x11.rti.amanzi.Value\x12\x16\n\nproperties\x18\x0e \x03(\rB\x02\x10\x01\x12\x1d\n\x11\x63ustom_properties\x18\x0f \x03(\rB\x02\x10\x01\x42\t\n\x07id_type\"\xc7\x02\n\x08Geometry\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.rti.amanzi.Geometry.Type\x12\x13\n\x07lengths\x18\x02 \x03(\rB\x02\x10\x01\x12\x12\n\x06\x63oords\x18\x03 \x03(\x12\x42\x02\x10\x01\x12(\n\ngeometries\x18\x04 \x03(\x0b\x32\x14.rti.amanzi.Geometry\x12!\n\x06values\x18\r \x03(\x0b\x32\x11.rti.amanzi.Value\x12\x1d\n\x11\x63ustom_properties\x18\x0f \x03(\rB\x02\x10\x01\"}\n\x04Type\x12\t\n\x05POINT\x10\x00\x12\x0e\n\nMULTIPOINT\x10\x01\x12\x0e\n\nLINESTRING\x10\x02\x12\x13\n\x0fMULTILINESTRING\x10\x03\x12\x0b\n\x07POLYGON\x10\x04\x12\x10\n\x0cMULTIPOLYGON\x10\x05\x12\x16\n\x12GEOMETRYCOLLECTION\x10\x06\"|\n\x11\x46\x65\x61tureCollection\x12%\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x13.rti.amanzi.Feature\x12!\n\x06values\x18\r \x03(\x0b\x32\x11.rti.amanzi.Value\x12\x1d\n\x11\x63ustom_properties\x18\x0f \x03(\rB\x02\x10\x01\"\xa3\x01\n\x05Value\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x16\n\x0c\x64ouble_value\x18\x02 \x01(\x01H\x00\x12\x17\n\rpos_int_value\x18\x03 \x01(\x04H\x00\x12\x17\n\rneg_int_value\x18\x04 \x01(\x04H\x00\x12\x14\n\nbool_value\x18\x05 \x01(\x08H\x00\x12\x14\n\njson_value\x18\x06 \x01(\tH\x00\x42\x0c\n\nvalue_typeb\x06proto3')
)



_GEOMETRY_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='rti.amanzi.Geometry.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='POINT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTIPOINT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINESTRING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTILINESTRING', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POLYGON', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTIPOLYGON', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEOMETRYCOLLECTION', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=431,
  serialized_end=556,
)
_sym_db.RegisterEnumDescriptor(_GEOMETRY_TYPE)


_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='rti.amanzi.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='geometry', full_name='rti.amanzi.Feature.geometry', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='rti.amanzi.Feature.id', index=1,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_id', full_name='rti.amanzi.Feature.int_id', index=2,
      number=12, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='rti.amanzi.Feature.values', index=3,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='rti.amanzi.Feature.properties', index=4,
      number=14, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_properties', full_name='rti.amanzi.Feature.custom_properties', index=5,
      number=15, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='id_type', full_name='rti.amanzi.Feature.id_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=44,
  serialized_end=226,
)


_GEOMETRY = _descriptor.Descriptor(
  name='Geometry',
  full_name='rti.amanzi.Geometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='rti.amanzi.Geometry.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lengths', full_name='rti.amanzi.Geometry.lengths', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coords', full_name='rti.amanzi.Geometry.coords', index=2,
      number=3, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='geometries', full_name='rti.amanzi.Geometry.geometries', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='rti.amanzi.Geometry.values', index=4,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_properties', full_name='rti.amanzi.Geometry.custom_properties', index=5,
      number=15, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GEOMETRY_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=556,
)


_FEATURECOLLECTION = _descriptor.Descriptor(
  name='FeatureCollection',
  full_name='rti.amanzi.FeatureCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='rti.amanzi.FeatureCollection.features', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='rti.amanzi.FeatureCollection.values', index=1,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_properties', full_name='rti.amanzi.FeatureCollection.custom_properties', index=2,
      number=15, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=682,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='rti.amanzi.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_value', full_name='rti.amanzi.Value.string_value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='rti.amanzi.Value.double_value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_int_value', full_name='rti.amanzi.Value.pos_int_value', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neg_int_value', full_name='rti.amanzi.Value.neg_int_value', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='rti.amanzi.Value.bool_value', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='json_value', full_name='rti.amanzi.Value.json_value', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value_type', full_name='rti.amanzi.Value.value_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=685,
  serialized_end=848,
)

_FEATURE.fields_by_name['geometry'].message_type = _GEOMETRY
_FEATURE.fields_by_name['values'].message_type = _VALUE
_FEATURE.oneofs_by_name['id_type'].fields.append(
  _FEATURE.fields_by_name['id'])
_FEATURE.fields_by_name['id'].containing_oneof = _FEATURE.oneofs_by_name['id_type']
_FEATURE.oneofs_by_name['id_type'].fields.append(
  _FEATURE.fields_by_name['int_id'])
_FEATURE.fields_by_name['int_id'].containing_oneof = _FEATURE.oneofs_by_name['id_type']
_GEOMETRY.fields_by_name['type'].enum_type = _GEOMETRY_TYPE
_GEOMETRY.fields_by_name['geometries'].message_type = _GEOMETRY
_GEOMETRY.fields_by_name['values'].message_type = _VALUE
_GEOMETRY_TYPE.containing_type = _GEOMETRY
_FEATURECOLLECTION.fields_by_name['features'].message_type = _FEATURE
_FEATURECOLLECTION.fields_by_name['values'].message_type = _VALUE
_VALUE.oneofs_by_name['value_type'].fields.append(
  _VALUE.fields_by_name['string_value'])
_VALUE.fields_by_name['string_value'].containing_oneof = _VALUE.oneofs_by_name['value_type']
_VALUE.oneofs_by_name['value_type'].fields.append(
  _VALUE.fields_by_name['double_value'])
_VALUE.fields_by_name['double_value'].containing_oneof = _VALUE.oneofs_by_name['value_type']
_VALUE.oneofs_by_name['value_type'].fields.append(
  _VALUE.fields_by_name['pos_int_value'])
_VALUE.fields_by_name['pos_int_value'].containing_oneof = _VALUE.oneofs_by_name['value_type']
_VALUE.oneofs_by_name['value_type'].fields.append(
  _VALUE.fields_by_name['neg_int_value'])
_VALUE.fields_by_name['neg_int_value'].containing_oneof = _VALUE.oneofs_by_name['value_type']
_VALUE.oneofs_by_name['value_type'].fields.append(
  _VALUE.fields_by_name['bool_value'])
_VALUE.fields_by_name['bool_value'].containing_oneof = _VALUE.oneofs_by_name['value_type']
_VALUE.oneofs_by_name['value_type'].fields.append(
  _VALUE.fields_by_name['json_value'])
_VALUE.fields_by_name['json_value'].containing_oneof = _VALUE.oneofs_by_name['value_type']
DESCRIPTOR.message_types_by_name['Feature'] = _FEATURE
DESCRIPTOR.message_types_by_name['Geometry'] = _GEOMETRY
DESCRIPTOR.message_types_by_name['FeatureCollection'] = _FEATURECOLLECTION
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), dict(
  DESCRIPTOR = _FEATURE,
  __module__ = 'protobuf.rti.geometry_pb2'
  # @@protoc_insertion_point(class_scope:rti.amanzi.Feature)
  ))
_sym_db.RegisterMessage(Feature)

Geometry = _reflection.GeneratedProtocolMessageType('Geometry', (_message.Message,), dict(
  DESCRIPTOR = _GEOMETRY,
  __module__ = 'protobuf.rti.geometry_pb2'
  # @@protoc_insertion_point(class_scope:rti.amanzi.Geometry)
  ))
_sym_db.RegisterMessage(Geometry)

FeatureCollection = _reflection.GeneratedProtocolMessageType('FeatureCollection', (_message.Message,), dict(
  DESCRIPTOR = _FEATURECOLLECTION,
  __module__ = 'protobuf.rti.geometry_pb2'
  # @@protoc_insertion_point(class_scope:rti.amanzi.FeatureCollection)
  ))
_sym_db.RegisterMessage(FeatureCollection)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'protobuf.rti.geometry_pb2'
  # @@protoc_insertion_point(class_scope:rti.amanzi.Value)
  ))
_sym_db.RegisterMessage(Value)


_FEATURE.fields_by_name['properties']._options = None
_FEATURE.fields_by_name['custom_properties']._options = None
_GEOMETRY.fields_by_name['lengths']._options = None
_GEOMETRY.fields_by_name['coords']._options = None
_GEOMETRY.fields_by_name['custom_properties']._options = None
_FEATURECOLLECTION.fields_by_name['custom_properties']._options = None
# @@protoc_insertion_point(module_scope)
