# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/rti/history.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf.google import timestamp_pb2 as protobuf_dot_google_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/rti/history.proto',
  package='rti.amanzi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1aprotobuf/rti/history.proto\x12\nrti.amanzi\x1a\x1fprotobuf/google/timestamp.proto\"`\n\x07History\x12.\n\nmodifiedOn\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t\x12\x14\n\x0creferenceIds\x18\x03 \x03(\tb\x06proto3')
  ,
  dependencies=[protobuf_dot_google_dot_timestamp__pb2.DESCRIPTOR,])




_HISTORY = _descriptor.Descriptor(
  name='History',
  full_name='rti.amanzi.History',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modifiedOn', full_name='rti.amanzi.History.modifiedOn', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='rti.amanzi.History.comment', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='referenceIds', full_name='rti.amanzi.History.referenceIds', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=171,
)

_HISTORY.fields_by_name['modifiedOn'].message_type = protobuf_dot_google_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['History'] = _HISTORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

History = _reflection.GeneratedProtocolMessageType('History', (_message.Message,), dict(
  DESCRIPTOR = _HISTORY,
  __module__ = 'protobuf.rti.history_pb2'
  # @@protoc_insertion_point(class_scope:rti.amanzi.History)
  ))
_sym_db.RegisterMessage(History)


# @@protoc_insertion_point(module_scope)
