site_name: Amanzi TimeSeries Specification
nav:
  - Introduction: index.md
  - Supported Languages: languages.md
  - Reference: components.md
theme: material
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.details